Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-02, with the labels that each got.

#77 fix: onConnect() event issue for creating a new listener each time it…
  src/background/backgroundPage.ts
  src/ui/pages/Home/index.tsx
Labels: 🪲 bug, ⚙️ backgound scripts

#93 fix: semaphore proof generation
  demo/index.tsx
  demo/package-lock.json
  demo/package.json
  package-lock.json
  package.json
  scripts/mock-merkle-proof.ts
  src/background/backgroundPage.ts
  src/background/services/lock.ts
  src/background/services/protocols/rln.ts
  src/background/services/protocols/semaphore.ts
  src/background/services/zk-validator.ts
  src/background/zk-keeper.ts
  src/contentscripts/injected.ts
  src/contentscripts/proof/index.ts
  src/contentscripts/proof/semaphore.ts
  src/ui/popup.tsx
  src/util/constants.ts
Labels: 🪲 bug

#104 fix: issues with semaphore and rln boilerplate
  README.md
  clean.sh
  demo/index.tsx
  package-lock.json
  package.json
  scripts/serve.sh
  src/background/controllers/browser-utils.ts
  src/background/controllers/request-manager.ts
  src/background/services/approval.ts
  src/background/services/identity.ts
  src/background/services/lock.ts
  src/background/services/protocols/rln.ts
  src/background/zk-keeper.ts
  src/contentscripts/injected.ts
  src/contentscripts/proof/index.ts
  src/contentscripts/proof/rln.ts
  src/contentscripts/proof/semaphore.ts
  src/manifest.json
  src/server/globals.ts
  src/server/mock-merkle-proof.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/ConnectionModal/index.tsx
  src/ui/ducks/app.ts
  src/ui/ducks/requests.ts
  src/ui/pages/Onboarding/index.tsx
  src/ui/pages/Popup/index.tsx
  src/ui/store/configureAppStore.ts
  src/util/constants.ts
  src/util/pushMessage.ts
Labels: 🪲 bug

#113 fix: hide activity tab
  src/ui/pages/Home/index.tsx
Labels: 🛠 enhancement

#116 chore: optimize build
  package-lock.json
  package.json
  scripts/clean-dev.sh
  scripts/clean-prod.sh
  webpack.common.js
  webpack.dev.js
Labels: 🛠 enhancement

#117 feat: add approve step for rln proof generation
  src/background/zk-keeper.ts
  src/types/index.ts
  src/ui/components/ConfirmRequestModal/index.tsx
Labels: 🛠 enhancement

#118 chore: remove unsafe eval code from bundle
  package-lock.json
  package.json
  src/config/ejsMock.js
  webpack.common.js
Labels: 🛡️security

#121 chore: add dotenv package and support debug env variable
  .env.example
  .github/workflows/build.yml
  jest.config.json
  package-lock.json
  package.json
  src/background/backgroundPage.ts
  src/config/env.ts
  src/config/mock/ejsMock.js
  src/config/mock/resourceMock.js
  src/ui/popup.tsx
  src/ui/store/configureAppStore.ts
  webpack.common.js
Labels: 🛠 enhancement

#122 feat: add web3-react connectors layer
  .env.example
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/config/__tests__/env.test.ts
  src/config/__tests__/rpc.test.ts
  src/config/chains.ts
  src/config/env.ts
  src/config/rpc.ts
  src/connectors/__tests__/metamask.test.ts
  src/connectors/__tests__/mock.test.ts
  src/connectors/__tests__/utils.test.ts
  src/connectors/index.ts
  src/connectors/metamask.ts
  src/connectors/mock.ts
  src/connectors/utils.ts
  src/static/chains.json
  src/ui/ducks/web3.ts
  webpack.common.js
Labels: 🛠 enhancement

#123 enhacement: copy zkeyfiles to the dist folder
  .gitignore
  .prettierignore
  demo/index.tsx
  src/background/services/zk-validator.ts
  src/background/zk-keeper.ts
  src/contentscripts/injected.ts
  src/manifest.json
  src/static/icons/logo-new.png
  src/types/index.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  webpack.common.js
  zkeyFiles/rln/rln.json
  zkeyFiles/rln/rln.wasm
  zkeyFiles/rln/rln.zkey
  zkeyFiles/semaphore/semaphore.json
  zkeyFiles/semaphore/semaphore.wasm
  zkeyFiles/semaphore/semaphore.zkey
Labels: 🛠 enhancement

#125 feat: add web3-react hook wrapper
  package-lock.json
  package.json
  src/config/const.ts
  src/config/mock/wallet.ts
  src/connectors/__tests__/utils.test.ts
  src/connectors/utils.ts
  src/ui/hooks/wallet/__tests__/useWallet.test.ts
  src/ui/hooks/wallet/index.ts
Labels: 🛠 enhancement

#127 feat: integrate web3 react package
  src/background/services/metamask-ethers.ts
  src/background/services/simple-storage.ts
  src/background/services/storage.ts
  src/background/zk-keeper.ts
  src/types/index.ts
  src/ui/components/CreateIdentityModal/__tests__/useCreateIdentityModal.test.ts
  src/ui/components/CreateIdentityModal/useCreateIdentityModal.ts
  src/ui/components/Header/index.tsx
  src/ui/ducks/hooks.ts
  src/ui/ducks/identities.ts
  src/ui/ducks/web3.ts
  src/ui/pages/Home/index.tsx
  src/ui/popup.tsx
  src/ui/services/ReduxConnector.ts
  src/ui/services/identity.ts
  src/ui/services/useMetaMask.ts
  src/ui/store/configureAppStore.ts
  src/web3-providers/EthersProivder.ts
  src/web3-providers/Metamask.ts
  src/web3-providers/index.ts
  src/web3-providers/types.ts
Labels: 🛠 enhancement
