Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-10, with the labels that each got.

#937 feat: update identity creation
  packages/app/src/background/services/credentials/__tests__/credentials.test.ts
  packages/app/src/background/services/credentials/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/config/mock/zk.ts
  packages/app/src/types/verifiableCredentials/index.ts
  packages/app/src/ui/components/DropdownButton/DropdownButton.tsx
  packages/app/src/ui/components/DropdownButton/__tests__/DropdownButton.test.tsx
  packages/app/src/ui/components/DropdownButton/__tests__/useDropdownButton.test.ts
  packages/app/src/ui/components/DropdownButton/index.ts
  packages/app/src/ui/components/DropdownButton/useDropdownButton.ts
  packages/app/src/ui/hooks/verifiableCredentials/__tests__/useCryptkeeperVerifiableCredentials.test.tsx
  packages/app/src/ui/pages/AddVerifiableCredential/__tests__/AddVerifiableCredential.test.tsx
  packages/app/src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/app/src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  packages/app/src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  packages/app/src/ui/pages/CreateIdentity/useCreateIdentity.ts
  packages/app/src/ui/pages/Identity/Identity.tsx
  packages/app/src/ui/pages/PresentVerifiableCredential/PresentVerifiableCredential.tsx
  packages/app/src/ui/pages/PresentVerifiableCredential/__tests__/PresentVerifiableCredential.test.tsx
  packages/app/src/ui/pages/PresentVerifiableCredential/__tests__/usePresentVerifiableCredential.test.ts
  packages/app/src/ui/pages/PresentVerifiableCredential/usePresentVerifiableCredential.ts
  packages/e2e/pages/cryptKeeper/Identities.ts
  packages/types/src/identity/index.ts
  packages/zk/src/identity/factory/__tests__/factory.test.ts
  packages/zk/src/identity/factory/index.ts
Labels: 🛠 enhancement

#944 refactor: one identity list
  packages/app/src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  packages/app/src/ui/pages/ConnectIdentity/__tests__/ConnectedIdentity.test.tsx
  packages/app/src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  packages/app/src/ui/pages/ConnectIdentity/useConnectIdentity.ts
Labels: 🛠 enhancement, 🖼️ ui logic, 🖌️ ui design

#962 feat: add import identity page
  packages/app/src/background/services/lock/index.ts
  packages/app/src/constants/paths.ts
  packages/app/src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
  packages/app/src/ui/pages/GroupMerkleProof/__tests__/useGroupMerkleProof.test.ts
  packages/app/src/ui/pages/Identity/__tests__/useIdentityPage.test.ts
  packages/app/src/ui/pages/ImportIdentity/ImportIdentity.tsx
  packages/app/src/ui/pages/ImportIdentity/__tests__/ImportIdentity.test.tsx
  packages/app/src/ui/pages/ImportIdentity/__tests__/useImportIdentity.test.ts
  packages/app/src/ui/pages/ImportIdentity/index.ts
  packages/app/src/ui/pages/ImportIdentity/useImportIdentity.ts
  packages/app/src/ui/pages/JoinGroup/__tests__/useJoinGroup.test.ts
  packages/app/src/ui/pages/Popup/Popup.tsx
  packages/app/src/ui/pages/RevealIdentityCommitment/__tests__/useRevealIdentityCommitment.test.ts
  packages/providers/src/services/event/types.ts
  packages/providers/src/services/handler/index.ts
Labels: 🌱 new feature

#972 fix: yup merkle source
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/validation/__tests__/merkleProofSourceValidator.test.ts
  packages/app/src/background/services/validation/source.ts
Labels: 🛠 enhancement

#966 fix: awaiting unlocked for Approval and ZkIdentity
  packages/app/src/background/services/approval/__tests__/approvalService.test.ts
  packages/app/src/background/services/approval/index.ts
  packages/app/src/background/services/base/Base.ts
  packages/app/src/background/services/base/index.ts
  packages/app/src/background/services/injector/InjectorHandler.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/lock/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/ui/components/ConfirmRequestModal/components/RlnProofModal/RlnProofModal.tsx
Labels: 🪲 bug

#975 feat: update input styles
  packages/app/src/config/mock/zk.ts
  packages/app/src/ui/components/BigNumberInput/BigNumberInput.tsx
  packages/app/src/ui/components/BigNumberInput/__tests__/BigNumberInput.test.tsx
  packages/app/src/ui/components/BigNumberInput/__tests__/useBigNumberInput.test.ts
  packages/app/src/ui/components/BigNumberInput/index.ts
  packages/app/src/ui/components/BigNumberInput/useBigNumberInput.ts
  packages/app/src/ui/components/ConfirmRequestModal/components/RlnProofModal/RlnProofModal.tsx
  packages/app/src/ui/components/ConfirmRequestModal/components/SemaphoreProofModal/SemaphoreProofModal.tsx
  packages/app/src/ui/components/IdentityList/Item/index.tsx
  packages/app/src/ui/components/Input/index.tsx
  packages/app/src/ui/components/Input/input.scss
  packages/app/src/ui/components/PasswordInput/PasswordInput.tsx
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/app/src/ui/pages/DownloadBackup/DownloadBackup.tsx
  packages/app/src/ui/pages/ImportIdentity/ImportIdentity.tsx
  packages/app/src/ui/pages/ImportIdentity/__tests__/ImportIdentity.test.tsx
  packages/app/src/ui/pages/ImportIdentity/__tests__/useImportIdentity.test.ts
  packages/app/src/ui/pages/ImportIdentity/useImportIdentity.ts
  packages/app/src/ui/pages/Login/Login.tsx
  packages/app/src/ui/pages/Onboarding/Onboarding.tsx
  packages/app/src/ui/pages/OnboardingBackup/OnboardingBackup.tsx
  packages/app/src/ui/pages/ResetPassword/ResetPassword.tsx
  packages/app/src/ui/pages/RevealMnemonic/RevealMnemonic.tsx
  packages/app/src/ui/pages/UploadBackup/UploadBackup.tsx
  packages/zk/src/index.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
  packages/zk/src/proof/protocols/index.ts
  packages/zk/src/proof/protocols/utils.ts
Labels: 🌱 new feature

#973 fix: protect external bandada apis
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/group/GroupService.ts
  packages/app/src/background/services/group/__tests__/GroupService.test.ts
  packages/app/src/background/services/group/index.ts
  packages/app/src/background/services/injector/Injector.ts
  packages/app/src/background/services/injector/InjectorHandler.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/constants/rpcInternalActions.ts
  packages/providers/src/constants/rpcExternalAction.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
Labels: 🪲 bug

#994 chore: add reviewers checklist to the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🛠 enhancement

#978 fix: check connected identity on `connect()`
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/approval/__tests__/approvalService.test.ts
  packages/app/src/background/services/approval/index.ts
  packages/app/src/background/services/base/Base.ts
  packages/app/src/background/services/injector/Injector.ts
  packages/app/src/background/services/injector/InjectorHandler.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/lock/__tests__/lockerService.test.ts
  packages/app/src/background/services/lock/index.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/ui/ducks/app.ts
  packages/app/src/ui/ducks/requests.ts
  packages/app/src/ui/pages/Login/__tests__/Login.test.tsx
  packages/app/src/ui/pages/Login/__tests__/useLogin.test.ts
  packages/app/src/ui/pages/Login/useLogin.ts
  packages/demo/index.tsx
Labels: 🪲 bug

#990 feat: import identity
  nx.json
  package.json
  packages/app/src/background/services/injector/InjectorHandler.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/config/mock/zk.ts
  packages/app/src/types/history/index.ts
  packages/app/src/ui/components/IdentityList/Item/index.tsx
  packages/app/src/ui/components/IdentityList/__tests__/IdentityList.test.tsx
  packages/app/src/ui/ducks/__tests__/identities.test.tsx
  packages/app/src/ui/pages/ConnectIdentity/__tests__/ConnectedIdentity.test.tsx
  packages/app/src/ui/pages/Home/__tests__/useHome.test.ts
  packages/app/src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx
  packages/app/src/ui/pages/Identity/Identity.tsx
  packages/app/src/ui/pages/Identity/__tests__/Idenity.test.tsx
  packages/app/src/ui/pages/RevealIdentityCommitment/RevealIdentityCommitment.tsx
  packages/types/src/identity/index.ts
  packages/types/src/index.ts
  packages/zk/src/identity/factory/__tests__/factory.test.ts
  packages/zk/src/identity/factory/index.ts
  packages/zk/src/identity/protocols/__tests__/zkIdentitySemaphore.test.ts
  packages/zk/src/proof/protocols/__tests__/proofs.test.ts
  pnpm-lock.yaml
Labels: 🌱 new feature

#993 feat: import identity integration
  packages/app/src/background/contentScript.ts
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/config/mock/zk.ts
  packages/app/src/constants/rpcInternalActions.ts
  packages/app/src/ui/components/BigNumberInput/BigNumberInput.tsx
  packages/app/src/ui/ducks/__tests__/identities.test.tsx
  packages/app/src/ui/ducks/identities.ts
  packages/app/src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  packages/app/src/ui/pages/ConnectIdentity/connectIdentity.scss
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/app/src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  packages/app/src/ui/pages/CreateIdentity/useCreateIdentity.ts
  packages/app/src/ui/pages/ImportIdentity/ImportIdentity.tsx
  packages/app/src/ui/pages/ImportIdentity/__tests__/useImportIdentity.test.ts
  packages/app/src/ui/pages/ImportIdentity/useImportIdentity.ts
  packages/app/src/util/__tests__/numbers.test.ts
  packages/app/src/util/numbers.ts
  packages/demo/useCryptKeeper.ts
  packages/providers/src/services/event/types.ts
  packages/providers/src/services/handler/index.ts
  packages/types/src/identity/index.ts
  packages/types/src/index.ts
Labels: 🌱 new feature

#1006 feat: added temp identity change for demo
  packages/app/src/background/services/injector/Injector.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/demo/index.tsx
  packages/demo/useCryptKeeper.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/providers/src/sdk/interface.ts
  packages/types/src/approval/index.ts
Labels: 🛠 enhancement

#1011 fix: unlock approval and identity services
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/base/Base.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
Labels: 🪲 bug

#1012 feat: add approval event
  .github/PULL_REQUEST_TEMPLATE.md
  packages/app/src/background/services/approval/index.ts
  packages/demo/useCryptKeeper.ts
  packages/providers/src/services/event/types.ts
Labels: 🌱 new feature

#1013 fix: release workflow
  .github/workflows/publishPackages.yml
  packages/app/src/ui/theme.ts
  packages/providers/src/index.ts
  packages/types/src/index.ts
  packages/zk/src/index.ts
Labels: DevOps

#1014 fix: remove build sign
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
Labels: DevOps

#1015 fix: publish packages
  .github/workflows/publishPackages.yml
  packages/app/src/ui/theme.ts
  packages/providers/src/index.ts
Labels: DevOps

#1016 fix: publish packages
  .github/workflows/publishPackages.yml
  packages/app/src/ui/theme.ts
  packages/providers/src/index.ts
  packages/types/package.json
  packages/zk/package.json
Labels: DevOps

#1017 feat: import external identity
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/approval/__tests__/approvalService.test.ts
  packages/app/src/background/services/approval/index.ts
  packages/app/src/background/services/injector/Injector.ts
  packages/app/src/background/services/injector/InjectorHandler.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/constants/rpcInternalActions.ts
  packages/app/src/ui/pages/Popup/usePopup.ts
  packages/demo/index.tsx
  packages/demo/useCryptKeeper.ts
  packages/providers/src/constants/rpcExternalAction.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/providers/src/sdk/initializeInjectedProvider.ts
  packages/providers/src/sdk/interface.ts
  packages/providers/src/services/handler/index.ts
  packages/types/src/identity/index.ts
Labels: 🛠 enhancement, 🌱 new feature

#1026 test: import identity e2e
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/demo/index.tsx
  packages/e2e/pages/cryptKeeper/Identities.ts
  packages/e2e/tests/importExternalIdentity.test.ts
  packages/types/package.json
  packages/zk/package.json
Labels: 🕵️ testing

#1018 refactor: enhancing the demo react app
  packages/demo/index.tsx
  packages/demo/package.json
  packages/demo/public/index.html
  packages/demo/src/components/Bandada/Bandada.tsx
  packages/demo/src/components/Bandada/index.ts
  packages/demo/src/components/Connect/Connect.tsx
  packages/demo/src/components/Connect/index.ts
  packages/demo/src/components/ConnectedIdentity/ConnectedIdentity.tsx
  packages/demo/src/components/ConnectedIdentity/index.ts
  packages/demo/src/components/DisplayProof/DisplayProof.tsx
  packages/demo/src/components/DisplayProof/index.ts
  packages/demo/src/components/GetCommitment/GetCommitment.tsx
  packages/demo/src/components/GetCommitment/index.ts
  packages/demo/src/components/GetMetadata/GetMetadata.tsx
  packages/demo/src/components/GetMetadata/index.ts
  packages/demo/src/components/ImportIdentity/ImportIdentity.tsx
  packages/demo/src/components/ImportIdentity/index.ts
  packages/demo/src/components/RateLimitingNullifier/RateLimitingNullifier.tsx
  packages/demo/src/components/RateLimitingNullifier/index.ts
  packages/demo/src/components/Semaphore/Semaphore.tsx
  packages/demo/src/components/Semaphore/index.ts
  packages/demo/src/components/VerifiableCredentials/VerifiableCredentials.tsx
  packages/demo/src/components/VerifiableCredentials/index.ts
  packages/demo/src/constants/index.ts
  packages/demo/src/hooks/useCryptKeeper.ts
  packages/demo/src/index.tsx
  packages/demo/src/pages/Main/Main.tsx
  packages/demo/src/pages/Main/index.ts
  packages/demo/src/types/index.ts
  packages/demo/src/utils/index.ts
  packages/demo/tsconfig.json
Labels: 🛠 enhancement

#1040 test: add missing tests for the extension
  packages/app/jest.config.js
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/credentials/__tests__/credentials.test.ts
  packages/app/src/background/services/credentials/index.ts
  packages/app/src/offscreen/Offscreen.ts
  packages/app/src/offscreen/__tests__/offscreenController.test.ts
  packages/app/src/offscreen/index.ts
  packages/app/src/offscreen/mocks.ts
  packages/app/src/ui/components/VerifiableCredential/Display/__tests__/VerifiableCredentialDisplay.test.tsx
  packages/app/src/ui/components/VerifiableCredential/Item/VerifiableCredentialItem.tsx
  packages/app/src/ui/components/VerifiableCredential/Item/__tests__/VerifiableCredentialItem.test.tsx
  packages/app/src/ui/components/VerifiableCredential/Item/__tests__/useVerifiableCredentialItem.test.ts
  packages/app/src/ui/components/VerifiableCredential/Item/useVerifiableCredentialItem.ts
  packages/app/src/ui/ducks/__tests__/verifiableCredentials.test.tsx
  packages/app/src/ui/ducks/verifiableCredentials.ts
  packages/app/src/ui/hooks/verifiableCredentials/__tests__/useCryptkeeperVerifiableCredentials.test.tsx
  packages/app/src/ui/hooks/verifiableCredentials/useCryptkeeperVerifiableCredentials.ts
  packages/app/src/ui/pages/AddVerifiableCredential/__tests__/AddVerifiableCredential.test.tsx
  packages/app/src/ui/pages/AddVerifiableCredential/__tests__/useAddVerifiableCredential.test.ts
  packages/app/src/ui/pages/AddVerifiableCredential/useAddVerifiableCredential.ts
  packages/app/src/ui/pages/PresentVerifiableCredential/usePresentVerifiableCredential.ts
  packages/app/src/util/__tests__/credentials.test.ts
  packages/app/src/util/credentials.ts
Labels: 🕵️ testing

#1046 feat: derive import identities from seed phrase
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/config/mock/wallet.ts
  packages/app/src/ui/components/DropdownButton/DropdownButton.tsx
  packages/app/src/ui/components/DropdownButton/__tests__/DropdownButton.test.tsx
  packages/app/src/ui/components/DropdownButton/index.ts
  packages/app/src/ui/ducks/__tests__/identities.test.tsx
  packages/app/src/ui/hooks/wallet/__tests__/useSignatureOptions.test.ts
  packages/app/src/ui/hooks/wallet/index.ts
  packages/app/src/ui/hooks/wallet/useSignatureOptions.ts
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/app/src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  packages/app/src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  packages/app/src/ui/pages/CreateIdentity/useCreateIdentity.ts
  packages/app/src/ui/pages/ImportIdentity/ImportIdentity.tsx
  packages/app/src/ui/pages/ImportIdentity/__tests__/ImportIdentity.test.tsx
  packages/app/src/ui/pages/ImportIdentity/__tests__/useImportIdentity.test.ts
  packages/app/src/ui/pages/ImportIdentity/useImportIdentity.ts
  packages/app/src/ui/pages/PresentVerifiableCredential/PresentVerifiableCredential.tsx
  packages/app/src/ui/services/identity/__tests__/identity.test.ts
  packages/app/src/ui/services/identity/index.ts
  packages/e2e/pages/cryptKeeper/Identities.ts
  packages/e2e/tests/importExternalIdentity.test.ts
  packages/types/src/identity/index.ts
  packages/zk/src/identity/factory/index.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
  pnpm-lock.yaml
Labels: 🌱 new feature

#1075 feat: add connection service
  packages/app/src/background/services/approval/index.ts
  packages/app/src/background/services/base/Base.ts
  packages/app/src/background/services/connection/ConnectionService.ts
  packages/app/src/background/services/connection/__tests__/ConnectionService.test.ts
  packages/app/src/background/services/connection/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/providers/src/services/event/types.ts
  packages/types/src/identity/index.ts
  packages/types/src/index.ts
Labels: 🌱 new feature
