Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-04, with the labels that each got.

#202 feat: add validation for onboarding page
  jest.config.json
  package-lock.json
  package.json
  src/background/backgroundPage.ts
  src/background/controllers/browserUtils.ts
  src/background/services/__tests__/identityService.test.ts
  src/background/services/identity.ts
  src/config/mock/wallet.ts
  src/ui/components/ConfirmRequestModal/__tests__/ConfirmRequestModal.test.tsx
  src/ui/components/Header/__tests__/Header.test.tsx
  src/ui/components/Header/index.tsx
  src/ui/components/Icon/index.tsx
  src/ui/components/Input/index.tsx
  src/ui/components/Input/input.scss
  src/ui/components/Menuable/Menuable.tsx
  src/ui/hooks/validation/__tests__/useValidationResolver.test.ts
  src/ui/hooks/validation/index.ts
  src/ui/hooks/wallet/__tests__/useWallet.test.ts
  src/ui/hooks/wallet/index.ts
  src/ui/pages/Home/Home.tsx
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/useHome.ts
  src/ui/pages/Onboarding/Onboarding.tsx
  src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx
  src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
  src/ui/pages/Onboarding/onboarding.scss
  src/ui/pages/Onboarding/useOnboarding.ts
Labels: 🛠 enhancement

#212 chore: upgrade rlnjs pacakge from npm registry
  package-lock.json
  package.json
Labels: 🛠 enhancement

#213 feat: disable random identity
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  src/background/services/__tests__/identityService.test.ts
  src/background/services/identity.ts
  src/config/__tests__/features.test.ts
  src/config/features.ts
  src/setupTests.ts
  src/ui/pages/CreateIdentity/CreateIdentity.tsx
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  webpack.common.js
Labels: 🖼️ ui logic, ⚙️ backgound identity service, 🌱 new feature

#239 feat: route configs for pages
  src/constants/paths.ts
  src/ui/pages/Popup/Popup.tsx
  src/ui/pages/Popup/__tests__/Popup.test.tsx
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
  zkeyFiles/rln/rln.json
  zkeyFiles/rln/rln.wasm
  zkeyFiles/rln/rln.zkey
Labels: 🛠 enhancement, 🖼️ ui logic

#243 fix: detect metamask wallet installed
  package-lock.json
  package.json
  src/config/mock/wallet.ts
  src/ui/components/Header/__tests__/Header.test.tsx
  src/ui/components/Header/index.tsx
  src/ui/hooks/wallet/__tests__/useWallet.test.ts
  src/ui/hooks/wallet/index.ts
  src/ui/popup.tsx
  src/util/__tests__/browser.test.ts
  src/util/browser.ts
Labels: 🪲 bug, 🖼️ ui logic

#244 test: setup playwright
  .eslintignore
  .eslintrc.js
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .gitignore
  .prettierignore
  demo/package.json
  e2e/constants/index.ts
  e2e/fixtures/index.ts
  e2e/helpers/account.ts
  e2e/tests/initialization.test.ts
  jest.config.json
  package-lock.json
  package.json
  playwright.config.ts
  tsconfig.json
Labels: 🕵️ testing, DevOps

#245 chore: get active identity data (commitment + web2provider)
  demo/index.tsx
  demo/package-lock.json
  demo/package.json
  src/background/services/__tests__/identityService.test.ts
  src/background/services/identity.ts
  src/background/zkKeeper.ts
  src/constants/rpcActions.ts
  src/contentScripts/index.ts
  src/contentScripts/injected.ts
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/popup.tsx
Labels: 🛠 enhancement

#210 feature: show/hide password onboarding
  src/types/index.ts
  src/ui/components/Checkbox/checkbox.scss
  src/ui/components/Checkbox/index.tsx
  src/ui/components/ConfirmRequestModal/ConfirmRequestModal.tsx
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/ConnectionApprovalModal.tsx
  src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/DefaultApprovalModal.tsx
  src/ui/components/ConfirmRequestModal/components/ProofModal/ProofModal.tsx
  src/ui/components/ConfirmRequestModal/confirmModal.scss
  src/ui/components/FullModal/FullModal.tsx
  src/ui/components/FullModal/FullModalContent.tsx
  src/ui/components/FullModal/FullModalFooter.tsx
  src/ui/components/FullModal/FullModalHeader.tsx
  src/ui/components/FullModal/fullModal.scss
  src/ui/components/Input/index.tsx
  src/ui/components/PasswordInput/ConfirmPasswordInput.tsx
  src/ui/components/PasswordInput/PasswordInput.tsx
  src/ui/components/PasswordInput/index.tsx
  src/ui/components/PasswordInput/passwordInput.scss
  src/ui/pages/Login/Login.tsx
  src/ui/pages/Login/__tests__/Login.test.tsx
  src/ui/pages/Login/__tests__/useLogin.test.ts
  src/ui/pages/Login/login.scss
  src/ui/pages/Login/useLogin.ts
  src/ui/pages/Onboarding/Onboarding.tsx
  src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx
  src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
  src/ui/pages/Onboarding/onboarding.scss
  src/ui/pages/Onboarding/useOnboarding.ts
Labels: 🛠 enhancement, 🖼️ ui logic

#249 fix: removing `genExternalNullifier()`
  demo/index.tsx
  demo/package-lock.json
  demo/package.json
  src/background/services/protocols/__tests__/protocols.test.ts
  src/background/services/protocols/rln.ts
  src/background/services/protocols/utils.ts
  src/custom.d.ts
  src/types/index.ts
Labels: 🪲 bug, ⚙️ backgound rln protocol

#247 fix: confirm password input
  src/background/services/protocols/__tests__/utils.test.ts
  src/ui/components/Input/index.tsx
  src/ui/components/Input/input.scss
  src/ui/components/PasswordInput/ConfirmPasswordInput.tsx
  src/ui/components/PasswordInput/PasswordInput.tsx
  src/ui/components/PasswordInput/index.tsx
  src/ui/components/PasswordInput/passwordInput.scss
  src/ui/pages/Login/Login.tsx
  src/ui/pages/Login/__tests__/Login.test.tsx
  src/ui/pages/Onboarding/Onboarding.tsx
  src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx
Labels: 🛠 enhancement

#251 feat: return activity tab back
  jest.config.json
  src/popup.html
  src/setupTests.ts
  src/ui/components/Menuable/Menuable.tsx
  src/ui/ducks/__tests__/app.test.tsx
  src/ui/ducks/__tests__/hooks.test.ts
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/__tests__/permissions.test.tsx
  src/ui/ducks/__tests__/requests.test.tsx
  src/ui/pages/Home/Home.tsx
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Home/components/TabList/TabList.tsx
  src/ui/pages/Home/components/TabList/__tests__/TabList.test.tsx
  src/ui/pages/Home/components/TabList/tabListStyles.scss
  src/ui/pages/Home/useHome.ts
  src/ui/popup.tsx
  src/ui/services/provider/index.ts
  src/ui/theme.ts
Labels: 🖼️ ui logic, 🌱 new feature

#252 feat: add history service for identity events
  src/background/services/__tests__/identityService.test.ts
  src/background/services/history/__tests__/history.test.ts
  src/background/services/history/index.ts
  src/background/services/identity.ts
  src/background/zkKeeper.ts
  src/constants/rpcActions.ts
  src/types/index.ts
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
Labels: 🌱 new feature

#255 fix: bug #250 not persistent approvals
  src/background/services/approval.ts
  src/background/zkKeeper.ts
Labels: 🪲 bug, ⚙️ backgound approval service

#254 feat: remove history operation
  jest.config.json
  package-lock.json
  package.json
  src/background/services/history/__tests__/history.test.ts
  src/background/services/history/index.ts
  src/background/zkKeeper.ts
  src/config/mock/nanoidMock.js
  src/constants/rpcActions.ts
  src/types/index.ts
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
Labels: 🌱 new feature

#259 feat: sticky footer for home tab list
  src/ui/pages/Home/components/ActivityList/ActivityList.tsx
  src/ui/pages/Home/components/ActivityList/activityListStyles.scss
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/identityListStyles.scss
  src/ui/pages/Home/components/TabList/tabListStyles.scss
Labels: 🖌️ ui design

#261 test: add e2e tests for identities
  .github/workflows/e2e.yml
  demo/index.tsx
  e2e/fixtures/index.ts
  e2e/helpers/account.ts
  e2e/pages/BasePage.ts
  e2e/pages/CryptKeeper.ts
  e2e/pages/index.ts
  e2e/tests/identity.test.ts
  e2e/tests/initialization.test.ts
  playwright.config.ts
  src/background/services/identity.ts
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
Labels: 🕵️ testing

#262 fix: refactoring the types
  package-lock.json
  package.json
  src/background/backgroundPage.ts
  src/background/controllers/handler.ts
  src/background/services/protocols/utils.ts
  src/types/contentScript/index.ts
  src/types/duck/index.ts
  src/types/history/index.ts
  src/types/identity/index.ts
  src/types/index.ts
  src/types/proof/Merkle.ts
  src/types/proof/RLNProof.ts
  src/types/proof/SemaphoreProof.ts
  src/types/proof/ZkProof.ts
  src/types/proof/index.ts
  src/types/reactComponent/index.ts
  src/types/request/index.ts
  src/types/utility/index.ts
  src/ui/components/ConfirmRequestModal/ConfirmRequestModal.tsx
  src/ui/components/ConfirmRequestModal/components/ProofModal/ProofModal.tsx
  src/ui/components/ConfirmRequestModal/components/ProofModal/useProofModal.ts
Labels: 🛠 enhancement

#265 feat: add options page
  src/background/services/history/__tests__/history.test.ts
  src/background/services/history/index.ts
  src/constants/paths.ts
  src/ui/components/Header/__tests__/Header.test.tsx
  src/ui/components/Header/index.tsx
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Home/components/ActivityList/ActivityList.tsx
  src/ui/pages/Home/components/ActivityList/__tests__/ActivityList.test.tsx
  src/ui/pages/Home/components/ActivityList/__tests__/useActivityList.test.ts
  src/ui/pages/Home/components/ActivityList/activityListStyles.scss
  src/ui/pages/Home/components/ActivityList/useActivityList.ts
  src/ui/pages/Login/__tests__/Login.test.tsx
  src/ui/pages/Login/__tests__/useLogin.test.ts
  src/ui/pages/Login/useLogin.ts
  src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx
  src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
  src/ui/pages/Onboarding/useOnboarding.ts
  src/ui/pages/Popup/Popup.tsx
  src/ui/pages/Popup/__tests__/Popup.test.tsx
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
  src/ui/pages/Settings/Settings.tsx
  src/ui/pages/Settings/__tests__/Settings.test.tsx
  src/ui/pages/Settings/__tests__/useSettings.test.ts
  src/ui/pages/Settings/components/General/General.tsx
  src/ui/pages/Settings/components/General/index.ts
  src/ui/pages/Settings/components/__tests__/General.test.tsx
  src/ui/pages/Settings/components/index.ts
  src/ui/pages/Settings/index.ts
  src/ui/pages/Settings/useSettings.ts
  src/ui/styles.scss
  src/util/__tests__/browser.test.ts
  src/util/browser.ts
Labels: 🖼️ ui logic, 🌱 new feature

#266 test: add e2e tests for history operations
  e2e/fixtures/index.ts
  e2e/helpers/account.ts
  e2e/pages/cryptKeeper/Activity.ts
  e2e/pages/cryptKeeper/CryptKeeper.ts
  e2e/pages/cryptKeeper/Identities.ts
  e2e/pages/cryptKeeper/Settings.ts
  e2e/pages/cryptKeeper/index.ts
  e2e/pages/index.ts
  e2e/tests/identity.test.ts
  src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx
Labels: 🕵️ testing

#269 chore: adding no-public eslint rule
  .eslintrc.js
  e2e/pages/BasePage.ts
  e2e/pages/cryptKeeper/Activity.ts
  e2e/pages/cryptKeeper/CryptKeeper.ts
  e2e/pages/cryptKeeper/Identities.ts
  e2e/pages/cryptKeeper/Settings.ts
  src/background/controllers/browserUtils.ts
  src/background/controllers/handler.ts
  src/background/controllers/requestManager.ts
  src/background/identityDecorater.ts
  src/background/services/approval.ts
  src/background/services/history/index.ts
  src/background/services/identity.ts
  src/background/services/lock.ts
  src/background/services/notification.ts
  src/background/services/protocols/rln.ts
  src/background/services/protocols/semaphore.ts
  src/background/services/simpleStorage.ts
  src/background/services/validation/artifact.ts
  src/background/services/validation/merkle.ts
  src/background/services/wallet.ts
  src/background/zkKeeper.ts
  src/connectors/mock.ts
  src/contentScripts/proof/rln.ts
  src/contentScripts/proof/semaphore.ts
Labels: 🛠 enhancement

#270 Fix/refactor history service
  src/background/services/history/__tests__/history.test.ts
  src/background/services/history/index.ts
  src/background/services/history/types.ts
Labels: 🛠 enhancement

#272 fix: refactor zk proof service
  src/background/services/protocols/interfaces.ts
  src/background/services/zkProof/RLNProof.ts
  src/background/services/zkProof/SemaphoreProof.ts
  src/background/services/zkProof/ZkProof.ts
  src/background/services/zkProof/__tests__/proofs.test.ts
  src/background/services/zkProof/__tests__/utils.test.ts
  src/background/services/zkProof/index.ts
  src/background/services/zkProof/utils.ts
  src/background/zkKeeper.ts
  src/contentScripts/proof/__tests__/rln.test.ts
  src/contentScripts/proof/__tests__/semaphore.test.ts
  src/contentScripts/proof/rln.ts
  src/contentScripts/proof/semaphore.ts
  src/server/mockMerkleProof.ts
Labels: 🛠 enhancement

#268 chore: support mac-os, windows platforms
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  README.md
  e2e/fixtures/index.ts
  e2e/helpers/account.ts
  e2e/pages/cryptKeeper/Identities.ts
  e2e/tests/identity.test.ts
  e2e/tests/initialization.test.ts
  jest.config.json
  package-lock.json
  package.json
  playwright.config.ts
  webpack.common.js
Labels: 🛠 enhancement, 🕵️ testing

#280 test: add e2e tests for proof generation
  e2e/tests/proofGeneration.test.ts
  playwright.config.ts
  src/server/mockMerkleProof.ts
Labels: 🕵️ testing

#277 feat: add advanced settings tab
  .github/PULL_REQUEST_TEMPLATE.md
  e2e/pages/cryptKeeper/Identities.ts
  e2e/pages/cryptKeeper/Settings.ts
  e2e/tests/identity.test.ts
  src/background/services/zkIdentity/factory/index.ts
  src/background/services/zkIdentity/index.ts
  src/background/services/zkIdentity/services/ZkIdentityFactory.ts
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Settings/Settings.tsx
  src/ui/pages/Settings/__tests__/Settings.test.tsx
  src/ui/pages/Settings/__tests__/useSettings.test.ts
  src/ui/pages/Settings/components/Advanced/Advanced.tsx
  src/ui/pages/Settings/components/Advanced/index.ts
  src/ui/pages/Settings/components/__tests__/Advanced.test.tsx
  src/ui/pages/Settings/components/index.ts
  src/ui/pages/Settings/useSettings.ts
Labels: 🌱 new feature

#281 feat: backup service
  src/background/cryptKeeper.ts
  src/background/services/approval/__tests__/approvalService.test.ts
  src/background/services/approval/index.ts
  src/background/services/backup/BackupService.ts
  src/background/services/backup/__tests__/BackupService.test.ts
  src/background/services/backup/index.ts
  src/background/services/backup/types.ts
  src/background/services/lock/__tests__/lockService.test.ts
  src/background/services/lock/index.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/constants/rpcActions.ts
  src/types/backup/index.ts
  src/types/index.ts
Labels: 🌱 new feature, ⚙️ backgound scripts
