Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-03, with the labels that each got.

#128 refactor: general clean up
  demo/index.tsx
  package-lock.json
  package.json
  src/background/__tests__/identityDecorater.test.ts
  src/background/__tests__/identityFactory.test.ts
  src/background/backgroundPage.ts
  src/background/controllers/browserUtils.ts
  src/background/controllers/requestManager.ts
  src/background/identity-factory.test.ts
  src/background/identity-factory.ts
  src/background/identityDecorater.ts
  src/background/identityFactory.ts
  src/background/services/__tests__/simpleStorage.test.ts
  src/background/services/approval.ts
  src/background/services/identity.ts
  src/background/services/lock.ts
  src/background/services/protocols/__tests__/protocols.test.ts
  src/background/services/protocols/__tests__/utils.test.ts
  src/background/services/protocols/interfaces.ts
  src/background/services/protocols/rln.ts
  src/background/services/protocols/semaphore.ts
  src/background/services/protocols/utils.ts
  src/background/services/simpleStorage.ts
  src/background/services/zkValidator.ts
  src/background/shared/checkForLastError.ts
  src/background/shared/checkManifestV3.ts
  src/background/shared/initGlobals.ts
  src/background/zkKeeper.ts
  src/contentScripts/index.ts
  src/contentScripts/injected.ts
  src/contentScripts/proof/__tests__/rln.test.ts
  src/contentScripts/proof/__tests__/semaphore.test.ts
  src/contentScripts/proof/index.ts
  src/contentScripts/proof/rln.ts
  src/contentScripts/proof/semaphore.ts
  src/server/mockMerkleProof.ts
  src/setupTests.ts
  src/types/index.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/ducks/requests.ts
  src/ui/popup.tsx
  src/ui/services/identity/__tests__/identity.test.ts
  src/ui/services/identity/index.ts
  src/util/__tests__/account.test.ts
  src/util/__tests__/checkParameter.test.ts
  src/util/__tests__/postMessage.test.ts
  src/util/__tests__/pushMessage.test.ts
  src/util/account.ts
  src/util/checkParameter.ts
  src/util/postMessage.ts
  webpack.common.js
Labels: 🛠 enhancement

#132 fix: zkpr initialization for demo
  demo/index.tsx
  src/contentScripts/injected.ts
Labels: 🪲 bug

#134 fix: delete identity
  package-lock.json
  package.json
  src/background/appInit.ts
  src/background/controllers/browserUtils.ts
  src/background/services/approval.ts
  src/background/services/identity.ts
  src/background/services/lock.ts
  src/background/shared/initGlobals.ts
  src/custom.d.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/CreateIdentityModal/CreateIdentityModal.tsx
  src/ui/components/CreateIdentityModal/__tests__/CreateIdentityModal.test.tsx
  src/ui/components/FullModal/index.tsx
  src/ui/components/Icon/index.tsx
  src/ui/components/Menuable/index.tsx
  src/ui/components/Modal/index.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/Home/components/IdentityList/IdentityItem.tsx
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityItem.test.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Home/components/IdentityList/index.ts
  src/ui/pages/Home/components/index.ts
  src/ui/pages/Home/index.tsx
  tsconfig.json
Labels: 🪲 bug, ⚙️ backgound identity service

#135 feat: delete all identities
  src/background/services/__tests__/identityService.test.ts
  src/background/services/identity.ts
  src/background/services/simpleStorage.ts
  src/background/zkKeeper.ts
  src/setupTests.ts
  src/ui/ducks/identities.ts
  src/ui/pages/Home/home.scss
  src/ui/pages/Home/index.tsx
  src/util/constants.ts
  tsconfig.json
Labels: ⚙️ backgound identity service, 🌱 new feature

#137 feat: social icons
  package-lock.json
  package.json
  src/constants/index.ts
  src/static/icons/logo-new.png
  src/static/icons/logo.png
  src/static/icons/logo.svg
  src/types/index.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/CreateIdentityModal/CreateIdentityModal.tsx
  src/ui/components/CreateIdentityModal/__tests__/CreateIdentityModal.test.tsx
  src/ui/components/CreateIdentityModal/__tests__/useCreateIdentityModal.test.ts
  src/ui/components/CreateIdentityModal/useCreateIdentityModal.ts
  src/ui/components/Dropdown/Dropdown.tsx
  src/ui/components/Dropdown/IconOption.tsx
  src/ui/components/Dropdown/IconSingleValue.tsx
  src/ui/components/Dropdown/__test__/Dropdown.test.tsx
  src/ui/components/Dropdown/dropdown.scss
  src/ui/components/Dropdown/index.ts
  src/ui/components/Dropdown/index.tsx
  src/ui/popup.tsx
Labels: 🛠 enhancement, 🖌️ ui design

#136 refactor: approval service
  src/background/services/__tests__/approvalService.test.ts
  src/background/services/approval.ts
  src/background/zkKeeper.ts
  src/contentScripts/injected.ts
Labels: 🛠 enhancement

#138 feat: support disconnect wallet
  src/background/services/__tests__/walletService.test.ts
  src/background/services/wallet.ts
  src/background/zkKeeper.ts
  src/config/mock/wallet.ts
  src/connectors/mock.ts
  src/constants/index.ts
  src/constants/rpcActions.ts
  src/contentScripts/injected.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/ConnectionModal/index.tsx
  src/ui/components/Header/index.tsx
  src/ui/ducks/app.ts
  src/ui/ducks/identities.ts
  src/ui/ducks/requests.ts
  src/ui/hooks/wallet/__tests__/useWallet.test.ts
  src/ui/hooks/wallet/index.ts
  src/ui/pages/Home/index.tsx
  src/ui/pages/Login/index.tsx
  src/ui/pages/Onboarding/index.tsx
  src/util/__tests__/postMessage.test.ts
  src/util/__tests__/pushMessage.test.ts
Labels: 🌱 new feature

#139 refactor: lock service
  src/background/services/__tests__/approvalService.test.ts
  src/background/services/__tests__/identityService.test.ts
  src/background/services/__tests__/lockService.test.ts
  src/background/services/approval.ts
  src/background/services/identity.ts
  src/background/services/lock.ts
  src/background/zkKeeper.ts
  src/ui/hooks/wallet/__tests__/useWallet.test.ts
Labels: 🛠 enhancement

#143 feat: add notifications service and permission
  README.md
  src/background/services/__tests__/identityService.test.ts
  src/background/services/__tests__/notificationService.test.ts
  src/background/services/identity.ts
  src/background/services/notification.ts
  src/manifest.json
  src/setupTests.ts
Labels: 🌱 new feature

#130 fix: popup window size
  src/ui/components/ConfirmRequestModal/confirm-modal.scss
  src/ui/components/FullModal/full-modal.scss
  src/ui/pages/Popup/popup.scss
Labels: 🪲 bug

#144 chore: add bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: 📄 documentation

#167 chore: update demo dependencies and add dependabot trigger
  .github/dependabot.yml
  demo/index.html
  demo/index.tsx
  demo/package-lock.json
  demo/package.json
  package-lock.json
Labels: 🛠 enhancement, 🛡️security

#169 chore: migrate background service to new linter
  .eslintrc.js
  .eslintrc.new.js
  .prettierrc
  package-lock.json
  package.json
  src/background/controllers/requestManager.ts
  src/background/services/__tests__/approvalService.test.ts
  src/background/services/__tests__/identityService.test.ts
  src/background/services/__tests__/lockService.test.ts
  src/background/services/__tests__/notificationService.test.ts
  src/background/services/__tests__/simpleStorage.test.ts
  src/background/services/__tests__/walletService.test.ts
  src/background/services/approval.ts
  src/background/services/identity.ts
  src/background/services/lock.ts
  src/background/services/notification.ts
  src/background/services/protocols/__tests__/protocols.test.ts
  src/background/services/protocols/__tests__/utils.test.ts
  src/background/services/protocols/interfaces.ts
  src/background/services/protocols/rln.ts
  src/background/services/protocols/semaphore.ts
  src/background/services/protocols/utils.ts
  src/background/services/simpleStorage.ts
  src/background/services/wallet.ts
  src/background/services/zkValidator.ts
  src/background/shared/initGlobals.ts
  src/connectors/metamask.ts
  src/connectors/mock.ts
  src/contentScripts/index.ts
  src/contentScripts/injected.ts
  src/server/mockMerkleProof.ts
  src/setupTests.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/ConnectionModal/index.tsx
  src/ui/components/Menuable/index.tsx
  src/ui/components/Modal/index.tsx
  src/ui/ducks/identities.ts
  src/ui/hooks/wallet/index.ts
  src/ui/pages/Home/components/IdentityList/IdentityItem.tsx
  src/ui/pages/Login/index.tsx
  src/ui/pages/Onboarding/index.tsx
  src/ui/popup.tsx
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 🛠 enhancement

#170 chore: prepare for new linter
  .eslintrc.new.js
  package.json
  src/background/__tests__/identityDecorater.test.ts
  src/background/__tests__/identityFactory.test.ts
  src/background/appInit.ts
  src/background/backgroundPage.ts
  src/background/controllers/browserUtils.ts
  src/background/controllers/handler.ts
  src/background/controllers/requestManager.ts
  src/background/identityDecorater.ts
  src/background/identityFactory.ts
  src/background/services/protocols/rln.ts
  src/background/services/zkValidator.ts
  src/background/shared/checkForLastError.ts
  src/background/shared/importScripts.ts
  src/background/zkKeeper.ts
  src/config/__tests__/rpc.test.ts
  src/config/chains.ts
  src/config/mock/wallet.ts
  src/config/rpc.ts
  src/connectors/__tests__/utils.test.ts
  src/connectors/utils.ts
  src/constants/index.ts
  src/custom.d.ts
  src/server/index.ts
  src/server/mockMerkleProof.ts
  src/types/index.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/ConnectionModal/index.tsx
  src/ui/ducks/app.ts
  src/ui/ducks/identities.ts
  src/ui/ducks/requests.ts
  src/ui/hooks/wallet/index.ts
  src/ui/pages/Home/index.tsx
  src/util/__tests__/account.test.ts
  src/util/__tests__/checkParameter.test.ts
  src/util/__tests__/postMessage.test.ts
  src/util/__tests__/pushMessage.test.ts
  src/util/account.ts
  src/util/checkParameter.ts
  src/util/postMessage.ts
  src/util/pushMessage.ts
Labels: 🛠 enhancement

#171 chore: eslint fixes for content scripts
  .eslintrc.new.js
  src/contentScripts/index.ts
  src/contentScripts/injected.ts
  src/contentScripts/proof/__tests__/rln.test.ts
  src/contentScripts/proof/__tests__/semaphore.test.ts
  src/contentScripts/proof/rln.ts
  src/contentScripts/proof/semaphore.ts
  src/types/index.ts
Labels: 🛠 enhancement

#177 chore: update ui folder with new linter rules
  .eslintrc.new.js
  src/ui/components/ConnectionModal/index.tsx
  src/ui/ducks/app.ts
  src/ui/ducks/hooks.ts
  src/ui/ducks/identities.ts
  src/ui/ducks/requests.ts
  src/ui/hooks/wallet/__tests__/useWallet.test.ts
  src/ui/hooks/wallet/index.ts
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/Item/identityListItemStyles.scss
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityItem.test.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Home/components/IdentityList/identityListStyles.scss
  src/ui/pages/Home/components/Info/Info.tsx
  src/ui/pages/Home/components/Info/__tests__/Info.test.tsx
  src/ui/pages/Home/components/Info/index.ts
  src/ui/pages/Home/components/Info/infoStyles.scss
  src/ui/pages/Home/components/TabList/TabList.tsx
  src/ui/pages/Home/components/TabList/__tests__/TabList.test.tsx
  src/ui/pages/Home/components/TabList/index.ts
  src/ui/pages/Home/components/TabList/tabListStyles.scss
  src/ui/pages/Home/components/index.ts
  src/ui/pages/Home/home.scss
  src/ui/pages/Home/index.tsx
  src/ui/pages/Login/index.tsx
  src/ui/pages/Onboarding/index.tsx
  src/ui/pages/Popup/index.tsx
  src/ui/popup.tsx
  src/ui/services/identity/index.ts
  src/ui/store/configureAppStore.ts
Labels: 🛠 enhancement

#178 chore: apply new linter rules
  .eslintrc.js
  .eslintrc.new.js
  package-lock.json
  package.json
  src/background/backgroundPage.ts
  src/background/controllers/browserUtils.ts
  src/background/controllers/handler.ts
  src/background/controllers/requestManager.ts
  src/background/identityDecorater.ts
  src/background/services/approval.ts
  src/background/services/identity.ts
  src/background/services/protocols/rln.ts
  src/background/services/protocols/semaphore.ts
  src/background/services/simpleStorage.ts
  src/background/services/wallet.ts
  src/background/services/zkValidator.ts
  src/background/zkKeeper.ts
  src/connectors/mock.ts
  src/contentScripts/proof/rln.ts
  src/contentScripts/proof/semaphore.ts
  src/custom.d.ts
  src/setupTests.ts
  src/types/index.ts
  src/ui/components/Button/index.tsx
  src/ui/components/Checkbox/index.tsx
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/ConnectionModal/index.tsx
  src/ui/components/CreateIdentityModal/CreateIdentityModal.tsx
  src/ui/components/CreateIdentityModal/__tests__/CreateIdentityModal.test.tsx
  src/ui/components/CreateIdentityModal/__tests__/useCreateIdentityModal.test.ts
  src/ui/components/CreateIdentityModal/useCreateIdentityModal.ts
  src/ui/components/Dropdown/Dropdown.tsx
  src/ui/components/Dropdown/IconOption.tsx
  src/ui/components/Dropdown/IconSingleValue.tsx
  src/ui/components/Dropdown/__tests__/Dropdown.test.tsx
  src/ui/components/FullModal/index.tsx
  src/ui/components/Header/index.tsx
  src/ui/components/Icon/index.tsx
  src/ui/components/Input/index.tsx
  src/ui/components/Menuable/index.tsx
  src/ui/components/Modal/index.tsx
  src/ui/ducks/app.ts
  src/ui/ducks/identities.ts
  src/ui/ducks/requests.ts
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
  src/ui/pages/Home/components/Info/Info.tsx
  src/ui/pages/Home/components/TabList/TabList.tsx
  src/ui/pages/Home/index.tsx
  src/ui/pages/Login/index.tsx
  src/ui/pages/Onboarding/index.tsx
  src/ui/pages/Popup/index.tsx
Labels: 🛠 enhancement

#183 feat: support separate windows for request modals
  src/background/controllers/browserUtils.ts
  src/background/controllers/requestManager.ts
  src/background/zkKeeper.ts
  src/constants/index.ts
  src/constants/paths.ts
  src/constants/rpcActions.ts
  src/contentScripts/injected.ts
  src/types/index.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/CreateIdentityModal/index.ts
  src/ui/ducks/app.ts
  src/ui/ducks/identities.ts
  src/ui/pages/CreateIdentity/CreateIdentity.tsx
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/index.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Home/index.tsx
  src/ui/pages/Popup/index.tsx
Labels: 🛠 enhancement

#185 refactor: request modals
  src/config/mock/modal.ts
  src/setupTests.ts
  src/types/index.ts
  src/ui/components/Checkbox/index.tsx
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/ConnectionApprovalModal.tsx
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/__tests__/ConnectionApprovalModal.test.tsx
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/__tests__/useConnectionApprovalModal.test.ts
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/index.ts
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/useConnectionApprovalModal.ts
  src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/DefaultApprovalModal.tsx
  src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/__tests__/DefaultApprovalModal.test.tsx
  src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/index.ts
  src/ui/components/ConfirmRequestModal/components/ProofModal/ProofModal.tsx
  src/ui/components/ConfirmRequestModal/components/ProofModal/__tests__/ProofModal.test.tsx
  src/ui/components/ConfirmRequestModal/components/ProofModal/__tests__/useProofModal.test.ts
  src/ui/components/ConfirmRequestModal/components/ProofModal/index.ts
  src/ui/components/ConfirmRequestModal/components/ProofModal/useProofModal.ts
  src/ui/components/ConfirmRequestModal/components/index.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/ConnectionModal/index.tsx
  src/ui/hooks/wallet/__tests__/useWallet.test.ts
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Home/components/Info/__tests__/Info.test.tsx
  src/util/__tests__/postMessage.test.ts
Labels: 🛠 enhancement

#186 fix: clean pending requests
  README.md
  demo/index.tsx
  src/background/controllers/browserUtils.ts
  src/background/controllers/requestManager.ts
  src/background/services/__tests__/identityService.test.ts
  src/background/services/identity.ts
  src/background/zkKeeper.ts
  src/types/index.ts
  src/ui/ducks/identities.ts
Labels: 🛠 enhancement

#189 test: add tests for request and connection modals
  src/background/appInit.ts
  src/background/services/__tests__/zkValidator.test.ts
  src/background/services/validation/__tests__/artifactProofValidator.test.ts
  src/background/services/validation/__tests__/merkleProofValidator.test.ts
  src/background/services/validation/artifact.ts
  src/background/services/validation/index.ts
  src/background/services/validation/merkle.ts
  src/background/services/zkValidator.ts
  src/background/shared/__tests__/importScripts.test.ts
  src/background/shared/__tests__/initGlobals.test.ts
  src/background/shared/__tests__/utils.test.ts
  src/background/shared/checkForLastError.ts
  src/background/shared/importScripts.ts
  src/background/zkKeeper.ts
  src/ui/components/ConfirmRequestModal/ConfirmRequestModal.tsx
  src/ui/components/ConfirmRequestModal/__tests__/ConfirmRequestModal.test.tsx
  src/ui/components/ConfirmRequestModal/__tests__/useConfirmRequestModal.test.ts
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/__tests__/useConnectionApprovalModal.test.ts
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/useConnectionApprovalModal.ts
  src/ui/components/ConfirmRequestModal/components/ProofModal/__tests__/useProofModal.test.ts
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/ConfirmRequestModal/useConfirmRequestModal.ts
  src/ui/components/ConnectionModal/ConnectionModal.tsx
  src/ui/components/ConnectionModal/__tests__/ConnectionModal.test.tsx
  src/ui/components/ConnectionModal/__tests__/useConnectionModal.test.ts
  src/ui/components/ConnectionModal/index.tsx
  src/ui/components/ConnectionModal/useConnectionModal.ts
Labels: 🛠 enhancement

#190 fix: prevent changing active identity
  src/background/services/__tests__/identityService.test.ts
  src/background/services/identity.ts
Labels: 🪲 bug, ⚙️ backgound identity service

#196 test: add tests for background controllers
  src/background/controllers/__tests__/browserUtils.test.ts
  src/background/controllers/__tests__/handler.test.ts
  src/background/controllers/__tests__/requestManager.test.ts
  src/background/controllers/browserUtils.ts
  src/background/controllers/handler.ts
  src/background/controllers/requestManager.ts
  src/setupTests.ts
  src/types/index.ts
  src/ui/components/ConfirmRequestModal/__tests__/useConfirmRequestModal.test.ts
  src/ui/components/ConfirmRequestModal/useConfirmRequestModal.ts
  src/util/__tests__/pushMessage.test.ts
Labels: 🛠 enhancement

#199 feat: add react-hook-form library
  .eslintrc.js
  package-lock.json
  package.json
  src/background/backgroundPage.ts
  src/background/services/__tests__/lockService.test.ts
  src/background/services/lock.ts
  src/background/zkKeeper.ts
  src/contentScripts/index.ts
  src/setupTests.ts
  src/ui/components/Input/index.tsx
  src/ui/components/Menuable/Menuable.tsx
  src/ui/components/Menuable/useMenuable.ts
  src/ui/ducks/__tests__/app.test.tsx
  src/ui/ducks/app.ts
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
  src/ui/pages/Login/Login.tsx
  src/ui/pages/Login/__tests__/Login.test.tsx
  src/ui/pages/Login/__tests__/useLogin.test.ts
  src/ui/pages/Login/useLogin.ts
  src/ui/pages/Popup/Popup.tsx
  src/ui/pages/Popup/__tests__/Popup.test.tsx
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
Labels: 🛠 enhancement

#200 feat: form management integration
  .eslintrc.js
  src/background/services/__tests__/identityService.test.ts
  src/background/services/__tests__/lockService.test.ts
  src/background/services/identity.ts
  src/background/services/lock.ts
  src/config/chains.ts
  src/setupTests.ts
  src/ui/components/Button/index.tsx
  src/ui/components/Checkbox/index.tsx
  src/ui/components/ConfirmRequestModal/ConfirmRequestModal.tsx
  src/ui/components/ConfirmRequestModal/__tests__/ConfirmRequestModal.test.tsx
  src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/DefaultApprovalModal.tsx
  src/ui/components/ConfirmRequestModal/components/DefaultApprovalModal/__tests__/DefaultApprovalModal.test.tsx
  src/ui/components/ConfirmRequestModal/index.tsx
  src/ui/components/Dropdown/Dropdown.tsx
  src/ui/components/Dropdown/__tests__/Dropdown.test.tsx
  src/ui/components/FullModal/FullModal.tsx
  src/ui/components/FullModal/FullModalContent.tsx
  src/ui/components/FullModal/FullModalFooter.tsx
  src/ui/components/FullModal/FullModalHeader.tsx
  src/ui/components/Icon/index.tsx
  src/ui/components/Input/index.tsx
  src/ui/components/Menuable/Menuable.tsx
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/CreateIdentity/CreateIdentity.tsx
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/createIdentityStyles.scss
  src/ui/pages/CreateIdentity/index.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/Home/Home.tsx
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityItem.test.tsx
  src/ui/pages/Home/components/Info/Info.tsx
  src/ui/pages/Home/components/TabList/TabList.tsx
  src/ui/pages/Home/components/TabList/__tests__/TabList.test.tsx
  src/ui/pages/Home/index.tsx
  src/ui/pages/Login/Login.tsx
  src/ui/pages/Login/__tests__/Login.test.tsx
  src/ui/pages/Login/__tests__/useLogin.test.ts
  src/ui/pages/Login/index.tsx
  src/ui/pages/Login/useLogin.ts
  src/ui/pages/Onboarding/Onboarding.tsx
  src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx
  src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
  src/ui/pages/Onboarding/index.tsx
  src/ui/pages/Onboarding/useOnboarding.ts
  src/ui/pages/Popup/Popup.tsx
  src/ui/pages/Popup/__tests__/Popup.test.tsx
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/index.ts
  src/ui/pages/Popup/usePopup.ts
  src/ui/popup.tsx
Labels: 🛠 enhancement
