Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-07, with the labels that each got.

#574 feat: reset password screen
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  packages/app/src/config/__tests__/features.test.ts
  packages/app/src/config/features.ts
  packages/app/src/constants/paths.ts
  packages/app/src/setupTests.ts
  packages/app/src/ui/pages/Login/Login.tsx
  packages/app/src/ui/pages/Popup/Popup.tsx
  packages/app/src/ui/pages/Popup/usePopup.ts
  packages/app/src/ui/pages/Recover/Recover.tsx
  packages/app/src/ui/pages/Recover/__tests__/Recover.test.tsx
  packages/app/src/ui/pages/Recover/__tests__/useRecover.test.ts
  packages/app/src/ui/pages/Recover/recover.scss
  packages/app/src/ui/pages/Recover/useRecover.ts
  packages/app/src/ui/pages/ResetPassword/ResetPassword.tsx
  packages/app/src/ui/pages/ResetPassword/__tests__/ResetPassword.test.tsx
  packages/app/src/ui/pages/ResetPassword/__tests__/useResetPassword.test.ts
  packages/app/src/ui/pages/ResetPassword/index.ts
  packages/app/src/ui/pages/ResetPassword/useResetPassword.ts
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#584 feat: add check mnemonic rpc
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/wallet/__tests__/walletService.test.ts
  packages/app/src/background/services/wallet/index.ts
  packages/app/src/types/wallet/index.ts
  packages/app/src/ui/ducks/__tests__/app.test.tsx
  packages/app/src/ui/ducks/app.ts
  packages/app/src/ui/pages/Login/Login.tsx
  packages/app/src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
  packages/app/src/ui/pages/Recover/__tests__/Recover.test.tsx
  packages/app/src/ui/pages/Recover/__tests__/useRecover.test.ts
  packages/app/src/ui/pages/Recover/useRecover.ts
  packages/providers/src/constants/rpcAction.ts
Labels: 🌱 new feature, ⚙️ scripts

#598 refactor: move crypto logic from lock service
  packages/app/src/background/services/approval/__tests__/approvalService.test.ts
  packages/app/src/background/services/approval/index.ts
  packages/app/src/background/services/crypto/__tests__/crypto.test.ts
  packages/app/src/background/services/crypto/index.ts
  packages/app/src/background/services/history/__tests__/history.test.ts
  packages/app/src/background/services/history/index.ts
  packages/app/src/background/services/lock/__tests__/lockerService.test.ts
  packages/app/src/background/services/lock/index.ts
  packages/app/src/background/services/wallet/__tests__/walletService.test.ts
  packages/app/src/background/services/wallet/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
Labels: 🛠 enhancement

#615 feat: enable reset password feature
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  packages/app/src/config/__tests__/features.test.ts
  packages/app/src/config/features.ts
  packages/app/src/setupTests.ts
  packages/app/src/ui/pages/Login/Login.tsx
Labels: 🌱 new feature

#624 feat: supporting offscreen feature for chrome platform
  packages/app/manifest.chrome.json
  packages/app/src/background/backgroundPage.ts
  packages/app/src/background/shared/__tests__/utils.test.ts
  packages/app/src/background/shared/utils.ts
  packages/app/src/constants/index.ts
  packages/app/src/offscreen/__tests__/offscreenHtml.test.ts
  packages/app/src/offscreen/index.html
  packages/app/src/offscreen/index.ts
  packages/types/src/request/index.ts
  pnpm-lock.yaml
Labels: 🌱 new feature

#627 feat: onboarding with user mnemonic
  packages/app/jest.config.js
  packages/app/src/background/services/wallet/__tests__/walletService.test.ts
  packages/app/src/background/services/wallet/index.ts
  packages/app/src/ui/components/MnemonicInput/MnemonicInput.tsx
  packages/app/src/ui/ducks/app.ts
  packages/app/src/ui/hooks/validation/__tests__/useValidationResolver.test.ts
  packages/app/src/ui/hooks/validation/index.ts
  packages/app/src/ui/pages/GenerateMnemonic/GenerateMnemonic.tsx
  packages/app/src/ui/pages/GenerateMnemonic/__tests__/GenerateMnemonic.test.tsx
  packages/app/src/ui/pages/GenerateMnemonic/__tests__/useGenerateMnemonic.test.ts
  packages/app/src/ui/pages/GenerateMnemonic/useGenerateMnemonic.ts
  packages/app/src/ui/pages/Recover/__tests__/useRecover.test.ts
  packages/app/src/ui/pages/Recover/useRecover.ts
  packages/e2e/helpers/account.ts
  packages/e2e/pages/cryptKeeper/CryptKeeper.ts
  packages/e2e/pages/cryptKeeper/Recover.ts
  packages/e2e/tests/recover.test.ts
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#635 feat: add rpc access for controller
  packages/app/src/background/backgroundPage.ts
  packages/app/src/background/controllers/__tests__/handler.test.ts
  packages/app/src/background/controllers/handler.ts
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/ui/components/PermissionModal/PermissionModal.tsx
  packages/app/src/util/__tests__/browser.test.ts
  packages/app/src/util/browser.ts
Labels: 🌱 new feature

#626 feat: integrate forked `semaphore-protocol/proof`
  packages/proofs/semaphore-proof/LICENSE
  packages/proofs/semaphore-proof/README.md
  packages/proofs/semaphore-proof/build.tsconfig.json
  packages/proofs/semaphore-proof/package.json
  packages/proofs/semaphore-proof/src/calculateNullifierHash.ts
  packages/proofs/semaphore-proof/src/generateProof.ts
  packages/proofs/semaphore-proof/src/hash.ts
  packages/proofs/semaphore-proof/src/index.test.ts
  packages/proofs/semaphore-proof/src/index.ts
  packages/proofs/semaphore-proof/src/packProof.ts
  packages/proofs/semaphore-proof/src/types/index.ts
  packages/proofs/semaphore-proof/src/unpackProof.ts
  packages/proofs/semaphore-proof/src/verificationKeys.json
  packages/proofs/semaphore-proof/src/verifyProof.ts
  packages/proofs/semaphore-proof/tsconfig.json
  packages/proofs/semaphore-proof/types/ffjavascript/index.d.ts
  packages/proofs/semaphore-proof/types/snarkjs/index.d.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 🛠 enhancement

#646 feat: integrate `@cryptkeeperzk/semaphore-proof` package
  packages/app/package.json
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/injector/index.ts
  packages/app/src/background/shared/utils.ts
  packages/app/src/offscreen/Offscreen.ts
  packages/app/src/offscreen/__tests__/offscreenController.test.ts
  packages/app/src/offscreen/__tests__/offscreenHtml.test.ts
  packages/app/src/offscreen/index.ts
  packages/app/src/util/pushMessage.ts
  packages/app/tsconfig.build.json
  packages/app/tsconfig.json
  packages/app/webpack.common.js
  packages/demo/useCryptKeeper.ts
  packages/proofs/semaphore-proof/build.tsconfig.json
  packages/proofs/semaphore-proof/package.json
  packages/proofs/semaphore-proof/src/@types/ffjavascript/index.d.ts
  packages/proofs/semaphore-proof/src/@types/snarkjs/index.d.ts
  packages/proofs/semaphore-proof/tsconfig.build.json
  packages/proofs/semaphore-proof/tsconfig.json
  packages/providers/src/constants/rpcAction.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/types/src/contentScript/index.ts
  packages/types/src/proof/semaphoreProof.ts
  packages/types/src/request/index.ts
  packages/zk/src/proof/__tests__/zkProofRLN.test.ts
  packages/zk/src/proof/__tests__/zkProofSemaphore.test.ts
  packages/zk/src/proof/protocols/__tests__/proofs.test.ts
  pnpm-lock.yaml
Labels: 🛠 enhancement

#650 feat: merge backup with current data
  packages/app/src/background/services/approval/__tests__/approvalService.test.ts
  packages/app/src/background/services/approval/index.ts
  packages/app/src/background/services/backup/BackupService.ts
  packages/app/src/background/services/backup/__tests__/BackupService.test.ts
  packages/app/src/background/services/lock/index.ts
  packages/app/src/background/services/wallet/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/types/backup/index.ts
Labels: 🌱 new feature

#651 feat: backup upload integration
  packages/app/src/background/services/wallet/index.ts
  packages/app/src/ui/components/UploadInput/UploadInput.tsx
  packages/app/src/ui/ducks/__tests__/backup.test.ts
  packages/app/src/ui/ducks/backup.ts
  packages/app/src/ui/pages/UploadBackup/UploadBackup.tsx
  packages/app/src/ui/pages/UploadBackup/__tests__/useUploadBackup.test.ts
  packages/app/src/ui/pages/UploadBackup/useUploadBackup.ts
  packages/app/src/util/__tests__/file.test.ts
  packages/app/src/util/file.ts
Labels: 🌱 new feature

#657 fix: generating semaphore proofs in firefox with mv2
  packages/app/.eslintignore
  packages/app/src/background/appInit.ts
  packages/app/src/background/backgroundPage.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/injector/index.ts
  packages/app/src/background/services/notification/index.ts
  packages/app/src/background/shared/importScripts.ts
  packages/app/src/background/shared/subworkers.js
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/manifest/v3/manifest.firefox.json
  packages/app/webpack.common.js
Labels: 🪲 bug

#656 feat: enable backup
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  packages/app/src/background/services/crypto/CryptoService.ts
  packages/app/src/background/services/crypto/__tests__/crypto.test.ts
  packages/app/src/config/__tests__/features.test.ts
  packages/app/src/config/features.ts
  packages/app/src/setupTests.ts
  packages/app/src/ui/pages/Settings/components/Backup/Backup.tsx
  packages/app/src/ui/pages/Settings/components/__tests__/Backup.test.tsx
  packages/app/src/ui/pages/UploadBackup/UploadBackup.tsx
  packages/app/src/ui/pages/UploadBackup/__tests__/useUploadBackup.test.ts
  packages/app/src/ui/pages/UploadBackup/useUploadBackup.ts
Labels: 🌱 new feature

#661 feat: offline support
  .github/workflows/e2e.yml
  .gitignore
  .prettierignore
  packages/app/.lintstagedrc.json
  packages/app/src/background/services/backup/BackupService.ts
  packages/app/src/background/services/history/index.ts
  packages/app/src/background/services/lock/index.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/manifest/v3/manifest.firefox.json
  packages/app/src/popup.html
  packages/app/src/static/styles/font-awesome.min.css
  packages/app/src/static/styles/tailwind.min.css
  packages/app/src/static/webfonts/fa-brands-400.eot
  packages/app/src/static/webfonts/fa-brands-400.svg
  packages/app/src/static/webfonts/fa-brands-400.ttf
  packages/app/src/static/webfonts/fa-brands-400.woff
  packages/app/src/static/webfonts/fa-brands-400.woff2
  packages/app/src/static/webfonts/fa-regular-400.eot
  packages/app/src/static/webfonts/fa-regular-400.svg
  packages/app/src/static/webfonts/fa-regular-400.ttf
  packages/app/src/static/webfonts/fa-regular-400.woff
  packages/app/src/static/webfonts/fa-regular-400.woff2
  packages/app/src/static/webfonts/fa-solid-900.eot
  packages/app/src/static/webfonts/fa-solid-900.svg
  packages/app/src/static/webfonts/fa-solid-900.ttf
  packages/app/src/static/webfonts/fa-solid-900.woff
  packages/app/src/static/webfonts/fa-solid-900.woff2
  packages/app/src/ui/components/Dropdown/dropdown.scss
  packages/app/src/ui/components/Input/input.scss
  packages/app/src/ui/styles.scss
  packages/app/webpack.common.js
  packages/demo/.lintstagedrc.json
  packages/e2e/.lintstagedrc.json
  packages/e2e/playwright.config.ts
  packages/eslint-config-base/.lintstagedrc.json
  packages/eslint-config-react/.lintstagedrc.json
  packages/merkle-mock-server/.lintstagedrc.json
  packages/providers/.lintstagedrc.json
  packages/types/.lintstagedrc.json
  packages/zk/.lintstagedrc.json
Labels: 🛠 enhancement, 🖌️ ui design

#494 feat: add verifiable credential data types (#489)
  packages/app/src/types/index.ts
  packages/app/src/types/verifiableCredentials/index.ts
Labels: 🛠 enhancement

#664 feat: backup file format
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  packages/app/src/background/services/approval/__tests__/approvalService.test.ts
  packages/app/src/background/services/approval/index.ts
  packages/app/src/background/services/backup/BackupService.ts
  packages/app/src/background/services/backup/types.ts
  packages/app/src/background/services/crypto/CryptoService.ts
  packages/app/src/background/services/crypto/__tests__/crypto.test.ts
  packages/app/src/background/services/lock/__tests__/lockerService.test.ts
  packages/app/src/background/services/lock/index.ts
  packages/app/src/background/services/wallet/__tests__/walletService.test.ts
  packages/app/src/background/services/wallet/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/e2e/fixtures/index.ts
  packages/e2e/pages/cryptKeeper/Settings.ts
  packages/e2e/playwright.config.ts
  packages/e2e/tests/backup.test.ts
Labels: 🛠 enhancement, 🕵️ testing

#668 fix: app styles and e2e speed up
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .gitignore
  packages/app/src/background/controllers/__tests__/browserUtils.test.ts
  packages/app/src/background/controllers/browserUtils.ts
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/config/__tests__/env.test.ts
  packages/app/src/config/env.ts
  packages/app/src/setupTests.ts
  packages/app/src/ui/components/AccountMenu/AccountMenu.tsx
  packages/app/src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx
  packages/app/src/ui/components/Header/__tests__/Header.test.tsx
  packages/app/src/ui/components/IdentityList/IdentityList.tsx
  packages/app/src/ui/components/IdentityList/identityListStyles.scss
  packages/app/src/ui/ducks/__tests__/app.test.tsx
  packages/app/src/ui/ducks/app.ts
  packages/app/src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  packages/app/src/ui/pages/ConnectIdentity/connectIdentity.scss
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/app/src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  packages/app/src/ui/pages/GenerateMnemonic/GenerateMnemonic.tsx
  packages/app/src/ui/pages/Home/components/ActivityList/activityListStyles.scss
  packages/app/src/ui/pages/Home/components/TabList/TabList.tsx
  packages/app/src/ui/pages/Home/components/TabList/tabListStyles.scss
  packages/app/src/ui/pages/Home/home.scss
  packages/app/src/ui/pages/Login/Login.tsx
  packages/app/src/ui/pages/Login/login.scss
  packages/app/src/ui/pages/Onboarding/Onboarding.tsx
  packages/app/src/ui/pages/Onboarding/onboarding.scss
  packages/app/src/ui/pages/OnboardingBackup/OnboardingBackup.tsx
  packages/app/src/ui/pages/Settings/Settings.tsx
  packages/app/src/ui/pages/Settings/__tests__/Settings.test.tsx
  packages/app/src/ui/pages/Settings/__tests__/useSettings.test.ts
  packages/app/src/ui/pages/Settings/components/Backup/Backup.tsx
  packages/app/src/ui/pages/Settings/components/__tests__/Backup.test.tsx
  packages/app/src/ui/pages/Settings/settings.scss
  packages/app/src/ui/pages/Settings/useSettings.ts
  packages/app/src/ui/pages/UploadBackup/UploadBackup.tsx
  packages/app/src/ui/theme.ts
  packages/e2e/backups/0_backup.json
  packages/e2e/constants/index.ts
  packages/e2e/fixtures/index.ts
  packages/e2e/helpers/account.ts
  packages/e2e/pages/cryptKeeper/CryptKeeper.ts
  packages/e2e/pages/cryptKeeper/Settings.ts
  packages/e2e/tests/backup.test.ts
  packages/e2e/tests/identity.test.ts
  packages/e2e/tests/initialization.test.ts
  packages/e2e/tests/proofGeneration.test.ts
  packages/providers/src/constants/rpcAction.ts
Labels: 🪲 bug, 🖌️ ui design, 🕵️ testing
