Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-06, with the labels that each got.

#430 feat: switch account
  demo/useCryptKeeper.ts
  src/background/contentScript.ts
  src/background/cryptKeeper.ts
  src/background/services/event/types.ts
  src/background/services/wallet/__tests__/walletService.test.ts
  src/background/services/wallet/index.ts
  src/constants/rpcActions.ts
  src/providers/sdk/Base.ts
  src/setupTests.ts
  src/ui/components/AccountMenu/AccountMenu.tsx
  src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx
  src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts
  src/ui/components/AccountMenu/useAccountMenu.ts
  src/ui/ducks/__tests__/app.test.tsx
  src/ui/ducks/app.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/Home/Home.tsx
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/components/IdentityList/identityListStyles.scss
  src/ui/pages/Home/components/Info/Info.tsx
  src/ui/pages/Home/components/Info/__tests__/Info.test.tsx
  src/ui/pages/Home/useHome.ts
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
Labels: 🖼️ ui logic, 🌱 new feature, ⚙️ scripts

#438 feat: associate random identity with user address
  e2e/pages/cryptKeeper/Identities.ts
  src/background/services/zkIdentity/__test__/factory.test.ts
  src/background/services/zkIdentity/factory/index.ts
  src/background/services/zkIdentity/index.ts
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityItem.test.tsx
Labels: 🛠 enhancement

#444 fix: remove accounts
  demo/index.tsx
  demo/useCryptKeeper.ts
  e2e/tests/proofGeneration.test.ts
  src/background/contentScript.ts
  src/background/services/event/types.ts
  src/providers/sdk/Base.ts
  src/setupTests.ts
Labels: 🪲 bug

#458 refactor: background handler
  src/background/controllers/__tests__/requestManager.test.ts
  src/background/controllers/requestManager.ts
  src/background/cryptKeeper.ts
  src/background/services/approval/__tests__/approvalService.test.ts
  src/background/services/approval/index.ts
  src/background/services/injector/__tests__/injector.test.ts
  src/background/services/injector/index.ts
  src/background/services/injector/types.ts
  src/constants/rpcActions.ts
  src/providers/sdk/Base.ts
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/__tests__/useConnectionApprovalModal.test.ts
  src/ui/components/ConfirmRequestModal/components/ConnectionApprovalModal/useConnectionApprovalModal.ts
  src/ui/components/ConnectionModal/__tests__/useConnectionModal.test.ts
  src/ui/components/ConnectionModal/useConnectionModal.ts
  src/ui/ducks/__tests__/permissions.test.tsx
  src/ui/ducks/permissions.ts
Labels: 🛠 enhancement

#467 feat: connect identity page
  src/constants/paths.ts
  src/static/icons/loader.svg
  src/static/icons/localhost.svg
  src/static/icons/logo.svg
  src/ui/components/ConnectionModal/index.tsx
  src/ui/components/IdentityList/IdentityList.tsx
  src/ui/components/IdentityList/Item/identityListItemStyles.scss
  src/ui/components/IdentityList/Item/index.tsx
  src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
  src/ui/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/components/IdentityList/identityListStyles.scss
  src/ui/components/IdentityList/index.ts
  src/ui/components/PermissionModal/PermissionModal.tsx
  src/ui/components/PermissionModal/__tests__/PermissionModal.test.tsx
  src/ui/components/PermissionModal/__tests__/usePermissionModal.test.ts
  src/ui/components/PermissionModal/index.tsx
  src/ui/components/PermissionModal/usePermissionModal.ts
  src/ui/components/SiteFavicon/SiteFavicon.tsx
  src/ui/components/SiteFavicon/index.ts
  src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  src/ui/pages/ConnectIdentity/__tests__/ConnectedIdentity.test.tsx
  src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  src/ui/pages/ConnectIdentity/index.ts
  src/ui/pages/ConnectIdentity/useConnectIdentity.ts
  src/ui/pages/Home/Home.tsx
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/components/ActivityList/activityListStyles.scss
  src/ui/pages/Home/components/Info/Info.tsx
  src/ui/pages/Home/components/Info/__tests__/Info.test.tsx
  src/ui/pages/Home/components/index.ts
  src/ui/pages/Home/useHome.ts
  src/ui/pages/Popup/Popup.tsx
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#468 feat: connect identity integration ui
  package-lock.json
  package.json
  src/setupTests.ts
  src/ui/components/Dropdown/__tests__/Dropdown.test.tsx
  src/ui/components/IdentityList/IdentityList.tsx
  src/ui/components/IdentityList/Item/index.tsx
  src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
  src/ui/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/components/IdentityList/identityListStyles.scss
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  src/ui/pages/ConnectIdentity/__tests__/ConnectedIdentity.test.tsx
  src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  src/ui/pages/ConnectIdentity/useConnectIdentity.ts
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/popup.tsx
  src/ui/theme.ts
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#474 refactor: rename active identity to connected
  demo/index.tsx
  demo/types.ts
  demo/useCryptKeeper.ts
  src/background/cryptKeeper.ts
  src/background/services/injector/__tests__/injector.test.ts
  src/background/services/injector/index.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/background/services/zkIdentity/protocols/ZkIdentitySemaphore.ts
  src/background/services/zkIdentity/protocols/__test__/zkIdentitySemaphore.test.ts
  src/constants/rpcActions.ts
  src/providers/sdk/Base.ts
  src/types/identity/index.ts
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  src/ui/pages/ConnectIdentity/useConnectIdentity.ts
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/useHome.ts
Labels: ⚙️ identity service, ⚙️ scripts

#481 feat: create identity from connect screen
  src/background/services/zkIdentity/factory/index.ts
  src/background/services/zkIdentity/index.ts
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  src/ui/pages/ConnectIdentity/useConnectIdentity.ts
  src/ui/pages/CreateIdentity/CreateIdentity.tsx
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
Labels: 🖼️ ui logic, 🌱 new feature

#490 feat: demo host connection
  LICENSE
  demo/index.tsx
  demo/types.ts
  demo/useCryptKeeper.ts
  manifest.chrome.json
  manifest.firefox.json
  src/background/contentScript.ts
  src/background/controllers/browserUtils.ts
  src/background/cryptKeeper.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/constants/rpcActions.ts
  src/providers/sdk/Base.ts
  src/types/duck/identities.ts
  src/types/identity/index.ts
  src/ui/components/IdentityList/IdentityList.tsx
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  src/ui/pages/ConnectIdentity/useConnectIdentity.ts
  src/ui/pages/Home/Home.tsx
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/useHome.ts
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
  webpack.common.js
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#498 feat: delete connected identity
  demo/index.tsx
  e2e/tests/identity.test.ts
  src/ui/components/IdentityList/Item/index.tsx
  src/ui/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Settings/Settings.tsx
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#504 feat: connect identity from demo
  demo/index.tsx
  demo/types.ts
  demo/useCryptKeeper.ts
  e2e/helpers/account.ts
  e2e/pages/cryptKeeper/ConnectIdentity.ts
  e2e/pages/cryptKeeper/CryptKeeper.ts
  e2e/pages/cryptKeeper/Identities.ts
  e2e/tests/backup.test.ts
  e2e/tests/identity.test.ts
  e2e/tests/proofGeneration.test.ts
  src/background/cryptKeeper.ts
  src/background/services/injector/index.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/constants/rpcActions.ts
  src/providers/sdk/Base.ts
  src/types/forms/index.ts
  src/types/identity/index.ts
  src/types/index.ts
  src/types/request/index.ts
  src/ui/components/ConfirmRequestModal/ConfirmRequestModal.tsx
  src/ui/components/ConfirmRequestModal/__tests__/ConfirmRequestModal.test.tsx
  src/ui/components/ConfirmRequestModal/__tests__/useConfirmRequestModal.test.ts
  src/ui/components/ConfirmRequestModal/useConfirmRequestModal.ts
  src/ui/components/IdentityList/IdentityList.tsx
  src/ui/components/IdentityList/Item/identityListItemStyles.scss
  src/ui/components/IdentityList/Item/index.tsx
  src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/ConnectIdentity/ConnectIdentity.tsx
  src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  src/ui/pages/ConnectIdentity/useConnectIdentity.ts
  src/ui/pages/Home/Home.tsx
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/useHome.ts
  src/ui/pages/Popup/usePopup.ts
Labels: 🖼️ ui logic, ⚙️ identity service, 🌱 new feature

#519 feat: metamask connection indicator
  e2e/tests/backup.test.ts
  e2e/tests/identity.test.ts
  e2e/tests/initialization.test.ts
  e2e/tests/proofGeneration.test.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/connectors/__tests__/cryptKeeper.test.ts
  src/connectors/__tests__/utils.test.ts
  src/connectors/cryptKeeper.ts
  src/connectors/index.ts
  src/connectors/utils.ts
  src/types/hooks/index.ts
  src/types/identity/index.ts
  src/ui/components/AccountMenu/AccountMenu.tsx
  src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx
  src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts
  src/ui/components/AccountMenu/useAccountMenu.ts
  src/ui/components/Header/__tests__/Header.test.tsx
  src/ui/components/Header/index.tsx
  src/ui/hooks/wallet/__tests__/useCryptKeeperWallet.test.ts
  src/ui/hooks/wallet/useCryptKeeper.ts
  src/ui/hooks/wallet/useEthWallet.ts
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
Labels: 🛠 enhancement, 🖼️ ui logic, 🖌️ ui design

#520 chore: migrate to pnpm
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .npmrc
  .prettierignore
  README.md
  demo/package-lock.json
  demo/package.json
  demo/pnpm-lock.yaml
  package-lock.json
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/setupTests.ts
Labels: DevOps

#499 fix: firefox launch
  manifest.chrome.json
  manifest.firefox.json
  package.json
  pnpm-lock.yaml
  src/background/appInit.ts
  src/background/backgroundPage.ts
  src/background/contentScript.ts
  src/background/controllers/__tests__/browserUtils.test.ts
  src/background/controllers/browserUtils.ts
  src/background/services/backup/BackupService.ts
  src/background/services/history/index.ts
  src/background/services/injector/__tests__/injector.test.ts
  src/background/services/injector/index.ts
  src/background/services/lock/__tests__/lockerService.test.ts
  src/background/services/lock/index.ts
  src/background/services/notification/__tests__/notificationService.test.ts
  src/background/services/notification/index.ts
  src/background/services/storage/__tests__/simpleStorage.test.ts
  src/background/services/storage/index.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/setupTests.ts
  src/ui/popup.tsx
  src/ui/services/provider/index.ts
  src/util/__tests__/browser.test.ts
  src/util/__tests__/postMessage.test.ts
  src/util/__tests__/pushMessage.test.ts
  src/util/browser.ts
  src/util/postMessage.ts
  src/util/pushMessage.ts
Labels: 🪲 bug

#526 feat: update readme, icons
  .prettierignore
  README.md
  packages/app/src/static/icons/icon-128.png
  packages/app/src/static/icons/icon-16.png
  packages/app/src/static/icons/icon-48.png
Labels: 🖌️ ui design

#534 chore: eslint packages
  .gitignore
  package.json
  packages/app/.eslintignore
  packages/app/.eslintrc.js
  packages/app/package.json
  packages/app/webpack.common.js
  packages/app/webpack.prod.js
  packages/e2e/.eslintignore
  packages/e2e/.eslintrc.js
  packages/e2e/package.json
  packages/e2e/tsconfig.json
  packages/eslint-config-base/index.js
  packages/eslint-config-base/package.json
  packages/eslint-config-react/index.js
  packages/eslint-config-react/package.json
  pnpm-lock.yaml
Labels: 🛠 enhancement, DevOps

#539 chore: move common types to `@cryptkeeper/types`
  .github/workflows/build.yml
  .github/workflows/check.yml
  package.json
  packages/app/jest.config.json
  packages/app/package.json
  packages/app/src/types/contentScript/index.ts
  packages/app/src/types/duck/index.ts
  packages/app/src/types/history/index.ts
  packages/app/src/types/index.ts
  packages/app/src/types/proof/index.ts
  packages/app/tsconfig.build.json
  packages/app/webpack.common.js
  packages/demo/package.json
  packages/demo/types.ts
  packages/demo/useCryptKeeper.ts
  packages/e2e/package.json
  packages/eslint-config-base/.lintstagedrc.json
  packages/eslint-config-base/package.json
  packages/eslint-config-react/.lintstagedrc.json
  packages/eslint-config-react/package.json
  packages/types/.eslintignore
  packages/types/.eslintrc.js
  packages/types/.lintstagedrc.json
  packages/types/package.json
  packages/types/src/approval/index.ts
  packages/types/src/contentScript/index.ts
  packages/types/src/duck/identities.ts
  packages/types/src/duck/index.ts
  packages/types/src/identity/index.ts
  packages/types/src/index.ts
  packages/types/src/proof/index.ts
  packages/types/src/proof/merkle.ts
  packages/types/src/proof/rlnProof.ts
  packages/types/src/proof/semaphoreProof.ts
  packages/types/src/proof/zkProof.ts
  packages/types/src/request/index.ts
  packages/types/tsconfig.json
  pnpm-lock.yaml
  tsconfig.json
Labels: 🛠 enhancement, DevOps

#546 chore: move zk proof and identity to `@cryptkeeper/zk`
  packages/app/package.json
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/background/services/zkProof/__tests__/zkProofRln.test.ts
  packages/app/src/background/services/zkProof/__tests__/zkProofSemaphore.test.ts
  packages/app/src/providers/sdk/Base.ts
  packages/app/src/server/mockMerkleProof.ts
  packages/demo/package.json
  packages/zk/.eslintignore
  packages/zk/.eslintrc.js
  packages/zk/.lintstagedrc.json
  packages/zk/jest.config.json
  packages/zk/package.json
  packages/zk/src/identity/factory/__tests__/factory.test.ts
  packages/zk/src/identity/factory/index.ts
  packages/zk/src/identity/index.ts
  packages/zk/src/identity/protocols/ZkIdentitySemaphore.ts
  packages/zk/src/identity/protocols/__tests__/zkIdentitySemaphore.test.ts
  packages/zk/src/identity/protocols/index.ts
  packages/zk/src/index.ts
  packages/zk/src/proof/__tests__/zkProofRLN.test.ts
  packages/zk/src/proof/__tests__/zkProofSemaphore.test.ts
  packages/zk/src/proof/index.ts
  packages/zk/src/proof/protocols/RLNProof.ts
  packages/zk/src/proof/protocols/SemaphoreProof.ts
  packages/zk/src/proof/protocols/__tests__/proofs.test.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
  packages/zk/src/proof/protocols/index.ts
  packages/zk/src/proof/protocols/types.ts
  packages/zk/src/proof/protocols/utils.ts
  packages/zk/src/proof/zkProofService.ts
  packages/zk/src/setupTests.ts
  packages/zk/tsconfig.build.json
  packages/zk/tsconfig.json
  packages/zk/tsconfig.tests.json
  pnpm-lock.yaml
Labels: 🛠 enhancement

#536 chore: use jest-preset for packages with tests
  jest-preset.js
  package.json
  packages/app/jest.config.js
  packages/app/jest.config.json
  packages/app/package.json
  packages/demo/package.json
  packages/e2e/package.json
  packages/eslint-config-base/package.json
  packages/eslint-config-react/package.json
  packages/zk/jest.config.js
  packages/zk/jest.config.json
  pnpm-lock.yaml
Labels: 🛠 enhancement, 🕵️ testing, DevOps

#555 chore: move providers to `@cryptkeeper/providers`
  packages/app/jest.config.js
  packages/app/package.json
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/injectedScript.ts
  packages/app/src/background/services/approval/index.ts
  packages/app/src/config/mock/nanoeventsMock.js
  packages/app/src/connectors/__tests__/cryptKeeper.test.ts
  packages/app/src/connectors/cryptKeeper.ts
  packages/app/src/constants/index.ts
  packages/app/src/providers/index.ts
  packages/app/src/providers/sdk/index.ts
  packages/app/src/setupTests.ts
  packages/app/src/ui/ducks/__tests__/app.test.tsx
  packages/app/src/ui/ducks/__tests__/backup.test.ts
  packages/app/src/ui/ducks/__tests__/identities.test.tsx
  packages/app/src/ui/ducks/__tests__/permissions.test.tsx
  packages/app/src/ui/ducks/__tests__/requests.test.tsx
  packages/app/src/ui/ducks/app.ts
  packages/app/src/ui/ducks/backup.ts
  packages/app/src/ui/ducks/identities.ts
  packages/app/src/ui/ducks/permissions.ts
  packages/app/src/ui/ducks/requests.ts
  packages/app/src/util/__tests__/postMessage.test.ts
  packages/app/src/util/__tests__/pushMessage.test.ts
  packages/providers/.eslintignore
  packages/providers/.eslintrc.js
  packages/providers/.lintstagedrc.json
  packages/providers/package.json
  packages/providers/src/constants/index.ts
  packages/providers/src/constants/rpcAction.ts
  packages/providers/src/event/index.ts
  packages/providers/src/event/types.ts
  packages/providers/src/index.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/providers/src/sdk/index.ts
  packages/providers/src/sdk/initializeInjectedProvider.ts
  packages/providers/tsconfig.build.json
  packages/providers/tsconfig.json
  packages/providers/tsconfig.tests.json
  packages/types/src/duck/index.ts
  packages/types/src/duck/permissions.ts
  pnpm-lock.yaml
Labels: 🛠 enhancement

#558 chore: move merkle mock server to separate package
  README.md
  package.json
  packages/app/.eslintrc.js
  packages/app/jest.config.js
  packages/app/package.json
  packages/e2e/package.json
  packages/e2e/playwright.config.ts
  packages/merkle-mock-server/.eslintignore
  packages/merkle-mock-server/.eslintrc.js
  packages/merkle-mock-server/.lintstagedrc.json
  packages/merkle-mock-server/package.json
  packages/merkle-mock-server/src/globals.ts
  packages/merkle-mock-server/src/index.ts
  packages/merkle-mock-server/src/mockMerkleProof.ts
  packages/merkle-mock-server/tsconfig.json
  pnpm-lock.yaml
Labels: 🛠 enhancement

#557 feat: use `@cryptkeeperzk/providers` for demo
  packages/app/src/background/appInit.ts
  packages/app/src/background/contentScript.ts
  packages/app/src/background/injectedScript.ts
  packages/demo/.eslintignore
  packages/demo/.eslintrc.js
  packages/demo/.lintstagedrc.json
  packages/demo/README.md
  packages/demo/index.tsx
  packages/demo/package.json
  packages/demo/tsconfig.json
  packages/demo/types.ts
  packages/demo/useCryptKeeper.ts
  packages/providers/src/index.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/providers/src/sdk/initializeInjectedProvider.ts
  pnpm-lock.yaml
Labels: 🌱 new feature

#579 chore: optimize webpack prod
  packages/app/package.json
  packages/app/webpack.prod.js
  pnpm-lock.yaml
Labels: 🛠 enhancement

#578 feat: enhance cryptkeeperzk/provider
  packages/app/src/connectors/__tests__/cryptKeeper.test.ts
  packages/app/src/connectors/cryptKeeper.ts
  packages/app/src/setupTests.ts
  packages/demo/useCryptKeeper.ts
  packages/providers/README.md
  packages/providers/src/constants/index.ts
  packages/providers/src/event/EventEmitter.ts
  packages/providers/src/event/index.ts
  packages/providers/src/event/types.ts
  packages/providers/src/index.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/providers/src/sdk/index.ts
  packages/providers/src/sdk/initializeInjectedProvider.ts
Labels: 🛠 enhancement
