Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-09, with the labels that each got.

#796 fix: optimize firefox build and manifest
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .github/workflows/healthCheck.yml
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
  .prettierignore
  package.json
  packages/app/package.json
  packages/app/project.json
  packages/app/src/background/services/injector/index.ts
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/manifest/v3/manifest.firefox.json
  packages/app/src/static/icons/logo.png
  packages/app/webpack.common.js
  packages/app/webpack.prod.js
  packages/demo/project.json
  packages/eslint-config-base/project.json
  packages/eslint-config-react/project.json
  packages/manifest-bump/.eslintignore
  packages/manifest-bump/.eslintrc.js
  packages/manifest-bump/.lintstagedrc.json
  packages/manifest-bump/executors.json
  packages/manifest-bump/jest.config.js
  packages/manifest-bump/package.json
  packages/manifest-bump/project.json
  packages/manifest-bump/src/executors/bump/__tests__/bump.test.ts
  packages/manifest-bump/src/executors/bump/executor.ts
  packages/manifest-bump/src/executors/bump/mocks/v2/manifest.firefox.json
  packages/manifest-bump/src/executors/bump/mocks/v3/manifest.chrome.json
  packages/manifest-bump/src/executors/bump/mocks/v3/manifest.firefox.json
  packages/manifest-bump/src/executors/bump/schema.d.ts
  packages/manifest-bump/src/executors/bump/schema.json
  packages/manifest-bump/src/index.ts
  packages/manifest-bump/src/setupTests.ts
  packages/manifest-bump/tsconfig.build.json
  packages/manifest-bump/tsconfig.json
  packages/manifest-bump/tsconfig.tests.json
  packages/merkle-mock-server/project.json
  packages/providers/project.json
  packages/types/project.json
  packages/types/src/proof/rlnProof.ts
  packages/zk/project.json
  packages/zk/src/proof/protocols/RLNProof.ts
  packages/zk/src/proof/protocols/mocks.ts
  packages/zk/src/proof/zkProofService.ts
  pnpm-lock.yaml
Labels: 🪲 bug

#820 chore: bump rlnjs to 3.2.0
  .github/workflows/publishChrome.yml
  .github/workflows/webExtLint.yml
  package.json
  packages/app/package.json
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/injector/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/offscreen/__tests__/offscreenController.test.ts
  packages/app/src/offscreen/__tests__/offscreenHtml.test.ts
  packages/app/src/ui/components/ConfirmRequestModal/useConfirmRequestModal.ts
  packages/app/src/ui/pages/Login/__tests__/Login.test.tsx
  packages/app/src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx
  packages/app/src/ui/pages/ResetPassword/__tests__/ResetPassword.test.tsx
  packages/types/package.json
  packages/zk/package.json
  packages/zk/src/proof/protocols/SemaphoreProof.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
  packages/zk/src/proof/protocols/utils.ts
  pnpm-lock.yaml
Labels: DevOps, dependencies

#826 chore: release preparations for firefox
  .github/workflows/webExtLint.yml
  packages/app/src/background/shared/subworkers.js
Labels: DevOps

#827 fix: release pipeline
  .github/workflows/release.yml
  packages/app/project.json
  packages/demo/project.json
  packages/eslint-config-base/project.json
  packages/eslint-config-react/project.json
  packages/manifest-bump/project.json
  packages/merkle-mock-server/project.json
  packages/providers/project.json
  packages/types/project.json
  packages/zk/project.json
Labels: DevOps

#829 fix: firefox publish
  packages/app/project.json
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.firefox.json
  packages/providers/src/index.ts
Labels: DevOps

#830 fix: release versions
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  packages/app/src/setupTests.ts
  packages/providers/src/index.ts
Labels: DevOps

#831 fix: store publish
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  packages/app/src/setupTests.ts
  packages/providers/src/index.ts
Labels: DevOps

#798 feat: request connected identity commitment
  .husky/commit-msg
  packages/app/src/background/contentScript.ts
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/credentials/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/connectors/__tests__/cryptKeeper.test.ts
  packages/app/src/connectors/cryptKeeper.ts
  packages/app/src/constants/paths.ts
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/manifest/v3/manifest.firefox.json
  packages/app/src/setupTests.ts
  packages/app/src/types/history/index.ts
  packages/app/src/ui/components/ConfirmRequestModal/ConfirmRequestModal.tsx
  packages/app/src/ui/ducks/__tests__/identities.test.tsx
  packages/app/src/ui/ducks/identities.ts
  packages/app/src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx
  packages/app/src/ui/pages/Home/components/ActivityList/__tests__/ActivityListItem.test.tsx
  packages/app/src/ui/pages/Popup/Popup.tsx
  packages/app/src/ui/pages/Popup/usePopup.ts
  packages/app/src/ui/pages/RevealIdentityCommitment/RevealIdentityCommitment.tsx
  packages/app/src/ui/pages/RevealIdentityCommitment/__tests__/RevealIdentityCommitment.test.tsx
  packages/app/src/ui/pages/RevealIdentityCommitment/__tests__/useRevealIdentityCommitment.test.ts
  packages/app/src/ui/pages/RevealIdentityCommitment/index.ts
  packages/app/src/ui/pages/RevealIdentityCommitment/useRevealIdentityCommitment.ts
  packages/app/webpack.common.js
  packages/demo/index.tsx
  packages/demo/package.json
  packages/demo/useCryptKeeper.ts
  packages/e2e/tests/revealIdentityCommitment.test.ts
  packages/manifest-bump/project.json
  packages/manifest-bump/tsconfig.json
  packages/providers/src/constants/rpcAction.ts
  packages/providers/src/event/types.ts
  packages/providers/src/index.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/types/src/index.ts
  packages/zk/src/identity/factory/__tests__/factory.test.ts
  packages/zk/src/proof/__tests__/index.test.ts
  packages/zk/src/proof/__tests__/zkProofRLN.test.ts
  packages/zk/src/proof/__tests__/zkProofSemaphore.test.ts
  packages/zk/src/proof/index.ts
  packages/zk/src/proof/protocols/__tests__/proofs.test.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
  packages/zk/src/proof/protocols/index.ts
  packages/zk/src/proof/protocols/mocks.ts
  pnpm-lock.yaml
Labels: 🌱 new feature

#832 chore: use latest manifest version for release
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  packages/app/project.json
  packages/manifest-bump/project.json
Labels: DevOps

#841 feat: add bandada service
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .github/workflows/healthCheck.yml
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
  .github/workflows/webExtLint.yml
  packages/app/src/background/services/bandada/BandadaService.ts
  packages/app/src/background/services/bandada/__tests__/BandadaService.test.ts
  packages/app/src/background/services/bandada/index.ts
  packages/app/src/background/services/storage/__tests__/simpleStorage.test.ts
  packages/app/src/config/__tests__/env.test.ts
  packages/app/src/config/__tests__/rpc.test.ts
  packages/app/src/config/env.ts
  packages/app/src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts
  packages/app/src/ui/components/Dropdown/__tests__/Dropdown.test.tsx
  packages/app/src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
  packages/app/src/ui/components/VerifiableCredential/__tests__/VerifiableCredentialItem.test.tsx
  packages/app/src/ui/hooks/wallet/__tests__/useCryptKeeperWallet.test.ts
  packages/app/src/ui/hooks/wallet/__tests__/useEthWallet.test.ts
  packages/app/src/ui/pages/Home/components/TabList/__tests__/TabList.test.tsx
  packages/app/src/util/__tests__/postMessage.test.ts
  packages/app/src/util/__tests__/pushMessage.test.ts
  packages/types/src/group/index.ts
  packages/types/src/index.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
Labels: 🌱 new feature

#842 chore: setting mock server var endpoint
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .github/workflows/healthCheck.yml
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
  .github/workflows/webExtLint.yml
  docker-compose.yml
  packages/demo/useCryptKeeper.ts
  packages/zk/src/proof/protocols/utils.ts
Labels: 🛠 enhancement

#849 chore: add flag for hidding reveal identity
  .env.example
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/e2e.yml
  .github/workflows/healthCheck.yml
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
  .github/workflows/webExtLint.yml
  packages/demo/index.tsx
Labels: DevOps

#850 fix: e2e tests
  packages/demo/index.tsx
  packages/e2e/tests/revealIdentityCommitment.test.ts
Labels: 🪲 bug

#848 chore: moving docs repo into the monorepo
  .github/workflows/deployDemo.yml
  .github/workflows/deployDocs.yml
  docs/README.md
  docs/SUMMARY.md
  docs/book.toml
  docs/src/SUMMARY.md
  docs/src/cryptkeeper/_intro.md
  docs/src/cryptkeeper/features.md
  docs/src/cryptkeeper/overview.md
  docs/src/guides/_intro.md
  docs/src/guides/contributing.md
  docs/src/guides/integration/_intro.md
  docs/src/guides/integration/connect-to-extension.md
  docs/src/guides/integration/create-identity.md
  docs/src/guides/integration/generate-proof.md
  docs/src/guides/integration/inject-client.md
  docs/src/guides/integration/zkitter-examples.md
  docs/src/references/_intro.md
  docs/src/references/faq.md
  docs/src/references/terms.md
Labels: 📄 documentation

#857 docs: enhance some docs parts
  .github/workflows/deployDocs.yml
  docs/book.toml
  docs/src/SUMMARY.md
  docs/src/cryptkeeper/_intro.md
  docs/src/cryptkeeper/features.md
  docs/src/cryptkeeper/overview.md
  docs/src/guides/contributing.md
  docs/src/guides/integration/_intro.md
  docs/src/guides/integration/connect-to-extension.md
  docs/src/guides/integration/connect.md
  docs/src/guides/integration/create-identity.md
  docs/src/guides/integration/generate-proof.md
  docs/src/guides/integration/get-connected-identity.md
  docs/src/guides/integration/inject-client.md
  docs/src/guides/integration/zkitter-examples.md
  docs/src/resources/_intro.md
  docs/src/what-is-cryptkeeper/_intro.md
Labels: 📄 documentation

#855 feat: add group rpc methods for background
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/group/GroupService.ts
  packages/app/src/background/services/group/__tests__/GroupService.test.ts
  packages/app/src/background/services/group/index.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/config/mock/zk.ts
  packages/providers/src/constants/rpcAction.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/types/src/group/index.ts
  packages/types/src/index.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
  packages/zk/src/proof/protocols/utils.ts
Labels: 🌱 new feature

#765 feat: request verifiable presentation from user (#509)
  packages/app/src/background/contentScript.ts
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/credentials/__tests__/credentials.test.ts
  packages/app/src/background/services/credentials/__tests__/utils.test.ts
  packages/app/src/background/services/credentials/index.ts
  packages/app/src/background/services/credentials/utils.ts
  packages/app/src/constants/paths.ts
  packages/app/src/types/history/index.ts
  packages/app/src/types/index.ts
  packages/app/src/types/verifiableCredentials/index.ts
  packages/app/src/ui/components/VerifiableCredential/Item/VerifiableCredentialItem.tsx
  packages/app/src/ui/components/VerifiableCredential/Item/useVerifiableCredentialItem.ts
  packages/app/src/ui/components/VerifiableCredential/List/VerifiableCredentialList.tsx
  packages/app/src/ui/ducks/__tests__/verifiableCredentials.test.tsx
  packages/app/src/ui/ducks/verifiableCredentials.ts
  packages/app/src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx
  packages/app/src/ui/pages/Popup/Popup.tsx
  packages/app/src/ui/pages/Popup/usePopup.ts
  packages/app/src/ui/pages/PresentVerifiableCredential/PresentVerifiableCredential.tsx
  packages/app/src/ui/pages/PresentVerifiableCredential/__tests__/PresentVerifiableCredential.test.tsx
  packages/app/src/ui/pages/PresentVerifiableCredential/__tests__/usePresentVerifiableCredential.test.ts
  packages/app/src/ui/pages/PresentVerifiableCredential/index.ts
  packages/app/src/ui/pages/PresentVerifiableCredential/usePresentVerifiableCredential.ts
  packages/demo/index.tsx
  packages/demo/useCryptKeeper.ts
  packages/providers/src/constants/rpcAction.ts
  packages/providers/src/event/types.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/types/src/index.ts
  packages/types/src/verifiableCredentials/index.ts
  packages/types/src/verifiableCredentials/verifiableCredentials.ts
  packages/types/src/verifiableCredentials/verifiablePresentations.ts
Labels: 🌱 new feature

#881 test: group e2e tests
  packages/e2e/pages/cryptKeeper/CryptKeeper.ts
  packages/e2e/pages/cryptKeeper/Groups.ts
  packages/e2e/tests/groups.test.ts
Labels: 🕵️ testing

#896 chore: change release publisher
  .github/workflows/release.yml
Labels: DevOps

#910 chore: add release workflow for types and zk packages
  .github/workflows/publishPackages.yml
  packages/types/package.json
  packages/zk/package.json
Labels: DevOps

#925 chore: return release publisher
  .github/workflows/release.yml
Labels: DevOps
