Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-08, with the labels that each got.

#576 feat: rpc to delete verifiable credentials (#492)
  packages/app/package.json
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/credentials/__tests__/credentials.test.ts
  packages/app/src/background/services/credentials/__tests__/utils.test.ts
  packages/app/src/background/services/credentials/index.ts
  packages/app/src/background/services/credentials/utils.ts
  packages/app/src/types/backup/index.ts
  packages/app/src/types/history/index.ts
  packages/app/src/types/verifiableCredentials/index.ts
  packages/app/src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx
  packages/providers/src/constants/rpcAction.ts
  packages/types/src/index.ts
  packages/types/src/verifiableCredentials/index.ts
  pnpm-lock.yaml
Labels: 🛠 enhancement

#682 chore: build gpg signing
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
Labels: DevOps

#649 feat: integrate `RLN` fork with the provider
  .github/workflows/e2e.yml
  .github/workflows/healthCheck.yml
  packages/app/package.json
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/injector/index.ts
  packages/app/src/background/services/injector/types.ts
  packages/app/src/background/services/validation/__tests__/zkValidator.test.ts
  packages/app/src/background/services/validation/index.ts
  packages/app/src/background/shared/__tests__/utils.test.ts
  packages/app/src/background/shared/utils.ts
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/offscreen/Offscreen.ts
  packages/app/src/offscreen/__tests__/offscreenController.test.ts
  packages/app/src/offscreen/mocks.ts
  packages/app/src/util/pushMessage.ts
  packages/app/tsconfig.json
  packages/app/webpack.common.js
  packages/demo/index.tsx
  packages/demo/package.json
  packages/demo/useCryptKeeper.ts
  packages/e2e/playwright.config.ts
  packages/e2e/tests/proofGeneration.test.ts
  packages/proofs/rln-proof/package.json
  packages/proofs/rln-proof/src/circuit-wrapper.ts
  packages/proofs/rln-proof/src/rln.ts
  packages/proofs/rln-proof/tests/circuit-wrapper.test.ts
  packages/providers/package.json
  packages/providers/src/constants/rpcAction.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/types/package.json
  packages/types/src/proof/rlnProof.ts
  packages/types/src/proof/semaphoreProof.ts
  packages/types/src/proof/zkProof.ts
  packages/zk/package.json
  packages/zk/src/proof/__tests__/zkProofRLN.test.ts
  packages/zk/src/proof/__tests__/zkProofSemaphore.test.ts
  packages/zk/src/proof/protocols/RLNProof.ts
  packages/zk/src/proof/protocols/SemaphoreProof.ts
  packages/zk/src/proof/protocols/__tests__/proofs.test.ts
  packages/zk/src/proof/protocols/__tests__/utils.test.ts
  packages/zk/src/proof/protocols/index.ts
  packages/zk/src/proof/protocols/mocks.ts
  packages/zk/src/proof/protocols/utils.ts
  packages/zk/src/proof/zkProofService.ts
  pnpm-lock.yaml
  zkeyFiles/rln/rln.json
  zkeyFiles/rln/rln.wasm
  zkeyFiles/rln/rln.zkey
Labels: 🛠 enhancement

#684 feat: identity page
  packages/app/src/background/services/injector/__tests__/injector.test.ts
  packages/app/src/background/services/injector/index.ts
  packages/app/src/background/shared/__tests__/utils.test.ts
  packages/app/src/background/shared/utils.ts
  packages/app/src/constants/index.ts
  packages/app/src/constants/paths.ts
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/offscreen/Offscreen.ts
  packages/app/src/ui/components/IdentityList/Item/index.tsx
  packages/app/src/ui/components/IdentityList/Item/useIdentityItem.ts
  packages/app/src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
  packages/app/src/ui/components/IdentityList/__tests__/IdentityList.test.tsx
  packages/app/src/ui/ducks/__tests__/identities.test.tsx
  packages/app/src/ui/ducks/identities.ts
  packages/app/src/ui/hooks/url/__tests__/useUrlParam.test.ts
  packages/app/src/ui/hooks/url/index.ts
  packages/app/src/ui/pages/Identity/Identity.tsx
  packages/app/src/ui/pages/Identity/__tests__/Idenity.test.tsx
  packages/app/src/ui/pages/Identity/__tests__/useIdentityPage.test.ts
  packages/app/src/ui/pages/Identity/index.ts
  packages/app/src/ui/pages/Identity/useIdentityPage.ts
  packages/app/src/ui/pages/Popup/Popup.tsx
  packages/app/src/util/__tests__/browser.test.ts
  packages/app/src/util/browser.ts
  packages/e2e/.eslintignore
  packages/e2e/pages/cryptKeeper/Identities.ts
  packages/e2e/tests/identity.test.ts
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#689 refactor: identity list
  .github/workflows/deploy.yml
  packages/app/src/background/services/injector/index.ts
  packages/app/src/ui/components/ConfirmDangerModal/style.ts
  packages/app/src/ui/components/IdentityList/IdentityList.tsx
  packages/app/src/ui/components/IdentityList/Item/identityListItemStyles.scss
  packages/app/src/ui/components/IdentityList/Item/index.tsx
  packages/app/src/ui/components/IdentityList/Item/useIdentityItem.ts
  packages/app/src/ui/components/IdentityList/__tests__/IdentityList.test.tsx
  packages/app/src/ui/components/IdentityList/identityListStyles.scss
  packages/app/src/ui/theme.ts
  packages/app/src/util/pushMessage.ts
  packages/e2e/pages/cryptKeeper/Identities.ts
  packages/e2e/playwright.config.ts
Labels: 🛠 enhancement

#692 feat: support expand mode
  packages/app/src/background/controllers/__tests__/handler.test.ts
  packages/app/src/setupTests.ts
  packages/app/src/ui/components/AccountMenu/AccountMenu.tsx
  packages/app/src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx
  packages/app/src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts
  packages/app/src/ui/components/AccountMenu/useAccountMenu.ts
  packages/app/src/ui/components/Header/__tests__/Header.test.tsx
  packages/app/src/ui/components/IdentityList/IdentityList.tsx
  packages/app/src/ui/components/IdentityList/__tests__/IdentityItem.test.tsx
  packages/app/src/ui/components/IdentityList/__tests__/IdentityList.test.tsx
  packages/app/src/ui/components/MnemonicInput/__tests__/useMnemonicInput.test.ts
  packages/app/src/ui/components/PasswordInput/PasswordInput.tsx
  packages/app/src/ui/components/PermissionModal/__tests__/usePermissionModal.test.ts
  packages/app/src/ui/hooks/validation/index.ts
  packages/app/src/ui/pages/ConnectIdentity/__tests__/useConnectIdentity.test.ts
  packages/app/src/ui/pages/ConnectIdentity/useConnectIdentity.ts
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/app/src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  packages/app/src/ui/pages/CreateIdentity/useCreateIdentity.ts
  packages/app/src/ui/pages/DownloadBackup/__tests__/useDownloadBackup.test.ts
  packages/app/src/ui/pages/DownloadBackup/useDownloadBackup.ts
  packages/app/src/ui/pages/Home/__tests__/useHome.test.ts
  packages/app/src/ui/pages/Home/components/ActivityList/ActivityList.tsx
  packages/app/src/ui/pages/Home/components/ActivityList/activityListStyles.scss
  packages/app/src/ui/pages/Identity/__tests__/useIdentityPage.test.ts
  packages/app/src/ui/pages/Identity/useIdentityPage.ts
  packages/app/src/ui/pages/Onboarding/Onboarding.tsx
  packages/app/src/ui/pages/Onboarding/__tests__/Onboarding.test.tsx
  packages/app/src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
  packages/app/src/ui/pages/Onboarding/useOnboarding.ts
  packages/app/src/ui/pages/OnboardingBackup/__tests__/OnboardingBackup.test.tsx
  packages/app/src/ui/pages/OnboardingBackup/__tests__/useOnboardingBackup.test.ts
  packages/app/src/ui/pages/OnboardingBackup/useOnboardingBackup.ts
  packages/app/src/ui/pages/Recover/__tests__/useRecover.test.ts
  packages/app/src/ui/pages/Recover/useRecover.ts
  packages/app/src/ui/pages/ResetPassword/__tests__/ResetPassword.test.tsx
  packages/app/src/ui/pages/ResetPassword/__tests__/useResetPassword.test.ts
  packages/app/src/ui/pages/ResetPassword/useResetPassword.ts
  packages/app/src/ui/pages/RevealMnemonic/__tests__/useRevealMnemonic.test.ts
  packages/app/src/ui/pages/RevealMnemonic/useRevealMnemonic.ts
  packages/app/src/ui/pages/Settings/__tests__/useSettings.test.ts
  packages/app/src/ui/pages/Settings/useSettings.ts
  packages/app/src/ui/pages/UploadBackup/__tests__/useUploadBackup.test.ts
  packages/app/src/ui/pages/UploadBackup/useUploadBackup.ts
  packages/app/src/util/__tests__/browser.test.ts
  packages/app/src/util/browser.ts
  packages/e2e/pages/cryptKeeper/Identities.ts
  packages/e2e/pages/cryptKeeper/Settings.ts
  packages/e2e/tests/backup.test.ts
  packages/e2e/tests/identity.test.ts
Labels: 🖼️ ui logic, 🌱 new feature

#718 feat: hide identity commitment
  packages/app/src/background/contentScript.ts
  packages/app/src/background/cryptKeeper.ts
  packages/app/src/background/services/zkIdentity/__tests__/zkIdentity.test.ts
  packages/app/src/background/services/zkIdentity/index.ts
  packages/app/src/ui/components/FullModal/fullModal.scss
  packages/app/src/ui/components/IdentityList/IdentityList.tsx
  packages/app/src/ui/components/IdentityList/Item/index.tsx
  packages/app/src/ui/ducks/__tests__/identities.test.tsx
  packages/app/src/ui/ducks/identities.ts
  packages/app/src/ui/pages/CreateIdentity/CreateIdentity.tsx
  packages/app/src/ui/pages/Home/components/ActivityList/Item/activityListItemStyles.scss
  packages/app/src/ui/pages/Home/components/ActivityList/activityListStyles.scss
  packages/demo/index.tsx
  packages/demo/useCryptKeeper.ts
  packages/providers/src/constants/rpcAction.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
  packages/types/src/duck/identities.ts
  packages/types/src/identity/index.ts
Labels: 🛠 enhancement

#739 chore: make EventName an enum (#738)
  packages/app/src/background/contentScript.ts
  packages/app/src/background/services/credentials/index.ts
  packages/app/src/connectors/__tests__/cryptKeeper.test.ts
  packages/app/src/connectors/cryptKeeper.ts
  packages/demo/useCryptKeeper.ts
  packages/providers/src/event/index.ts
  packages/providers/src/event/types.ts
  packages/providers/src/sdk/CryptKeeperInjectedProvider.ts
Labels: 🛠 enhancement

#741 chore: release support
  .github/workflows/release.yml
  package.json
Labels: DevOps

#742 chore: skip root changelog generation [skip ci]
  package.json
Labels: DevOps

#743 chore: use pat for release pipeline [skip ci]
  .github/workflows/release.yml
Labels: DevOps

#744 chore: fix release pipeline [skip ci]
  .github/workflows/release.yml
  package.json
Labels: DevOps

#745 chore: fix release pipeline [skip ci]
  .github/workflows/release.yml
Labels: DevOps

#746 fix: release pipeline
  .prettierignore
  package.json
  packages/app/src/setupTests.ts
  packages/providers/src/index.ts
Labels: DevOps

#747 fix: release pipeline
  package.json
Labels: DevOps

#748 fix: release pipeline
  .github/workflows/release.yml
  packages/app/src/setupTests.ts
  packages/providers/src/index.ts
Labels: DevOps

#749 fix: release pipeline
  packages/app/project.json
  packages/providers/project.json
Labels: DevOps

#750 chore: release fixes
  .github/workflows/release.yml
  package.json
  packages/app/project.json
  packages/providers/project.json
Labels: DevOps

#751 fix: publish packages
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  package.json
  packages/providers/project.json
  pnpm-lock.yaml
Labels: DevOps

#752 fix: publish with pnpm
  .github/workflows/publishPackages.yml
  packages/providers/project.json
Labels: DevOps

#753 fix: tags for release
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
Labels: DevOps

#760 fix: store publish
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
Labels: DevOps

#769 fix: store publish
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
  packages/providers/src/index.ts
Labels: DevOps

#770 fix: signing key import
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
Labels: DevOps

#778 fix: gpg key import
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
Labels: DevOps

#779 fix: gpg signing order and args
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
Labels: DevOps

#781 fix: disable commit signing for release bot
  .github/workflows/release.yml
Labels: DevOps

#782 fix: use pat instead of github token
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
Labels: DevOps

#786 fix: release pipeline
  .github/workflows/publishChrome.yml
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  .github/workflows/release.yml
Labels: DevOps

#787 fix: release workflow
  .github/workflows/release.yml
Labels: DevOps

#788 fix: release pipeline
  .github/workflows/release.yml
Labels: DevOps

#789 fix: release workflow
  .github/workflows/release.yml
Labels: DevOps

#790 fix: change release publisher
  .github/workflows/release.yml
Labels: DevOps

#792 fix: firefox and providers publish
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  package.json
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/manifest/v3/manifest.firefox.json
  packages/providers/package.json
  packages/providers/src/index.ts
Labels: DevOps

#793 fix: firefox store publish
  .github/workflows/publishFirefox.yml
  .github/workflows/publishPackages.yml
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/manifest/v3/manifest.firefox.json
  packages/providers/src/index.ts
Labels: DevOps

#794 docs: updating README with RLN protocol
  README.md
  packages/app/src/manifest/v2/manifest.firefox.json
  packages/app/src/manifest/v3/manifest.chrome.json
  packages/app/src/manifest/v3/manifest.firefox.json
Labels: 📄 documentation
