Repository CryptKeeperZK/crypt-keeper-extension, pull requests merged in 2023-05, with the labels that each got.

#290 chore: update dev dependencies and change dependabot interval to daily
  .github/dependabot.yml
  demo/package-lock.json
  demo/package.json
  package-lock.json
  package.json
Labels: dependencies

#305 feat: enhance backup
  src/background/cryptKeeper.ts
  src/background/services/approval/__tests__/approvalService.test.ts
  src/background/services/approval/index.ts
  src/background/services/backup/BackupService.ts
  src/background/services/backup/__tests__/BackupService.test.ts
  src/background/services/backup/types.ts
  src/background/services/crypto/index.ts
  src/background/services/history/index.ts
  src/background/services/lock/__tests__/lockerService.test.ts
  src/background/services/lock/index.ts
  src/background/services/lock/types.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
Labels: ⚙️ backup service

#309 feat: add download backup file
  src/ui/pages/DownloadBackup/__tests__/useDownloadBackup.test.ts
  src/ui/pages/DownloadBackup/useDownloadBackup.ts
  src/util/__tests__/browser.test.ts
  src/util/browser.ts
Labels: 🖼️ ui logic

#310 test: add tests for services
  .eslintrc.js
  src/background/cryptKeeper.ts
  src/background/services/approval/__tests__/approvalService.test.ts
  src/background/services/approval/index.ts
  src/background/services/crypto/index.ts
  src/background/services/lock/__tests__/lockerService.test.ts
  src/background/services/lock/index.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/connectors/utils.ts
  src/contentScripts/injected.ts
  src/ui/components/Menuable/useMenuable.ts
Labels: 🕵️ testing

#326 feat: download backup notification
  package-lock.json
  package.json
  playwright.config.ts
  src/background/services/backup/BackupService.ts
  src/background/services/backup/__tests__/BackupService.test.ts
  src/background/services/crypto/__tests__/crypto.test.ts
  src/background/services/crypto/index.ts
  src/background/services/history/index.ts
  src/background/services/lock/index.ts
  src/background/services/zkIdentity/index.ts
  src/types/history/index.ts
  src/ui/ducks/__tests__/backup.test.ts
  src/ui/ducks/backup.ts
  src/ui/pages/Home/components/ActivityList/Item/ActivityListItem.tsx
Labels: 🌱 new feature, ⚙️ backup service

#337 test: add e2e tests for backup download
  .github/workflows/e2e.yml
  e2e/pages/cryptKeeper/Settings.ts
  e2e/tests/backup.test.ts
Labels: 🕵️ testing

#343 feat: add key storage service
  package-lock.json
  package.json
  src/background/services/key/__tests__/keyStorageService.test.ts
  src/background/services/key/index.ts
  src/background/services/key/types.ts
  src/background/services/mnemonic/__tests__/mnemonic.test.ts
  src/background/services/mnemonic/index.ts
  webpack.common.js
Labels: 🌱 new feature

#355 feat: mnemonic ui
  .github/CODEOWNERS
  src/constants/paths.ts
  src/setupTests.ts
  src/ui/components/RevealMnemonicInput/RevealMnemonicInput.tsx
  src/ui/components/RevealMnemonicInput/__tests__/RevealMnemonicInput.test.tsx
  src/ui/components/RevealMnemonicInput/__tests__/useRevealMnemonic.test.ts
  src/ui/components/RevealMnemonicInput/index.ts
  src/ui/components/RevealMnemonicInput/useRevealMnemonic.ts
  src/ui/hooks/timeout/__tests__/useTimeout.test.ts
  src/ui/hooks/timeout/index.ts
  src/ui/pages/Mnemonic/Mnemonic.tsx
  src/ui/pages/Mnemonic/__tests__/Mnemonic.test.tsx
  src/ui/pages/Mnemonic/__tests__/useMnemonic.test.ts
  src/ui/pages/Mnemonic/index.ts
  src/ui/pages/Mnemonic/useMnemonic.ts
  src/ui/pages/Popup/Popup.tsx
  src/util/__tests__/browser.test.ts
  src/util/browser.ts
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature

#345 feat: enhance content script
  .eslintrc.js
  README.md
  demo/index.tsx
  demo/types.ts
  demo/useCryptKeeper.ts
  package-lock.json
  package.json
  src/background/appInit.ts
  src/background/contentScript.ts
  src/background/cryptKeeper.ts
  src/background/injectedScript.ts
  src/background/services/event/index.ts
  src/background/services/event/types.ts
  src/background/services/zkIdentity/index.ts
  src/contentScripts/injected.ts
  src/manifest.chrome.json
  src/manifest.firefox.json
  src/providers/index.ts
  src/providers/initializeInjectedProvider.ts
  src/providers/sdk/Base.ts
  src/providers/sdk/index.ts
  src/types/approval/index.ts
  src/types/contentScript/index.ts
  src/types/duck/identities.ts
  src/types/duck/index.ts
  src/types/index.ts
  src/ui/components/PasswordInput/PasswordInput.tsx
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/Login/Login.tsx
  src/ui/pages/Onboarding/Onboarding.tsx
  webpack.common.js
Labels: 🛠 enhancement, 💉 injection-script

#361 feat: mnemonic integration
  e2e/pages/cryptKeeper/CryptKeeper.ts
  src/background/controllers/browserUtils.ts
  src/background/cryptKeeper.ts
  src/background/services/key/__tests__/keyStorageService.test.ts
  src/background/services/key/index.ts
  src/background/services/lock/__tests__/lockerService.test.ts
  src/background/services/lock/index.ts
  src/background/services/misc/__tests__/miscStorageService.test.ts
  src/background/services/misc/index.ts
  src/background/services/misc/types.ts
  src/background/services/wallet/__tests__/walletService.test.ts
  src/background/services/wallet/index.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/constants/rpcActions.ts
  src/popup.html
  src/types/index.ts
  src/types/misc/index.ts
  src/ui/components/Modal/modal.scss
  src/ui/components/RevealMnemonicInput/RevealMnemonicInput.tsx
  src/ui/components/RevealMnemonicInput/__tests__/RevealMnemonicInput.test.tsx
  src/ui/ducks/__tests__/app.test.tsx
  src/ui/ducks/app.ts
  src/ui/pages/Home/components/IdentityList/identityListStyles.scss
  src/ui/pages/Home/components/TabList/tabListStyles.scss
  src/ui/pages/Mnemonic/Mnemonic.tsx
  src/ui/pages/Mnemonic/__tests__/Mnemonic.test.tsx
  src/ui/pages/Mnemonic/__tests__/useMnemonic.test.ts
  src/ui/pages/Mnemonic/useMnemonic.ts
  src/ui/pages/Onboarding/__tests__/useOnboarding.test.ts
  src/ui/pages/Onboarding/useOnboarding.ts
  src/ui/pages/Popup/__tests__/Popup.test.tsx
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
  src/ui/styles.scss
  src/ui/theme.ts
Labels: 🖼️ ui logic, 🌱 new feature, ⚙️ scripts

#372 feat: sign with cryptkeeper
  package-lock.json
  package.json
  src/background/cryptKeeper.ts
  src/background/services/wallet/__tests__/walletService.test.ts
  src/background/services/wallet/index.ts
  src/background/services/wallet/types.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/types/duck/identities.ts
  src/types/duck/index.ts
  src/types/identity/index.ts
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/services/identity/__tests__/identity.test.ts
  src/ui/services/identity/index.ts
Labels: 🌱 new feature

#373 feat: support cryptkeeper identity creation
  demo/index.tsx
  e2e/pages/cryptKeeper/Identities.ts
  e2e/tests/backup.test.ts
  e2e/tests/identity.test.ts
  e2e/tests/proofGeneration.test.ts
  jest.config.json
  src/background/appInit.ts
  src/background/controllers/requestManager.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/config/mock/wallet.ts
  src/connectors/mock.ts
  src/providers/sdk/Base.ts
  src/ui/components/Icon/index.tsx
  src/ui/components/Menuable/MenuItem.tsx
  src/ui/components/Menuable/Menuable.tsx
  src/ui/components/Menuable/menuable.scss
  src/ui/components/Menuable/useMenuable.ts
  src/ui/components/Modal/index.tsx
  src/ui/ducks/identities.ts
  src/ui/pages/CreateIdentity/CreateIdentity.tsx
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/Home/components/IdentityList/IdentityList.tsx
  src/ui/pages/Home/components/IdentityList/__tests__/IdentityList.test.tsx
  src/ui/pages/Home/components/IdentityList/identityListStyles.scss
Labels: 🌱 new feature

#384 feat: multi accounts support
  package-lock.json
  package.json
  src/background/cryptKeeper.ts
  src/background/services/wallet/__tests__/walletService.test.ts
  src/background/services/wallet/index.ts
  src/background/services/wallet/types.ts
  src/background/services/zkIdentity/__test__/zkIdentity.test.ts
  src/background/services/zkIdentity/index.ts
  src/constants/rpcActions.ts
  src/types/backup/index.ts
  src/types/identity/index.ts
  src/types/index.ts
  src/types/wallet/index.ts
  src/ui/ducks/__tests__/app.test.tsx
  src/ui/ducks/__tests__/identities.test.tsx
  src/ui/ducks/app.ts
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
  src/ui/pages/Mnemonic/__tests__/useMnemonic.test.ts
  src/ui/pages/Mnemonic/useMnemonic.ts
  src/ui/services/identity/__tests__/identity.test.ts
  src/ui/services/identity/index.ts
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature, ⚙️ scripts

#396 feat: integrate cryptkeeper for web3-react
  src/background/cryptKeeper.ts
  src/config/mock/wallet.ts
  src/connectors/__tests__/cryptKeeper.test.ts
  src/connectors/__tests__/metamask.test.ts
  src/connectors/__tests__/utils.test.ts
  src/connectors/cryptKeeper.ts
  src/connectors/index.ts
  src/connectors/utils.ts
  src/constants/rpcActions.ts
  src/providers/initializeInjectedProvider.ts
  src/providers/sdk/Base.ts
  src/setupTests.ts
  src/ui/components/Header/__tests__/Header.test.tsx
  src/ui/components/Header/index.tsx
  src/ui/hooks/wallet/__tests__/useEthWallet.test.ts
  src/ui/hooks/wallet/index.ts
  src/ui/hooks/wallet/useEthWallet.ts
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/DownloadBackup/__tests__/DownloadBackup.test.tsx
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Home/__tests__/useHome.test.ts
  src/ui/pages/Home/components/IdentityList/Item/index.tsx
  src/ui/pages/Home/useHome.ts
  src/ui/pages/Mnemonic/Mnemonic.tsx
  src/ui/pages/Mnemonic/__tests__/Mnemonic.test.tsx
  src/ui/pages/Mnemonic/useMnemonic.ts
  src/ui/pages/Popup/__tests__/Popup.test.tsx
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
  src/ui/pages/Settings/__tests__/Settings.test.tsx
Labels: 🌱 new feature

#417 feat: web3-react bip39
  demo/index.tsx
  demo/types.ts
  demo/useCryptKeeper.ts
  src/background/contentScript.ts
  src/config/chains.ts
  src/config/mock/wallet.ts
  src/config/rpc.ts
  src/connectors/__tests__/cryptKeeper.test.ts
  src/connectors/__tests__/mock.test.ts
  src/connectors/__tests__/utils.test.ts
  src/connectors/cryptKeeper.ts
  src/connectors/index.ts
  src/connectors/utils.ts
  src/providers/sdk/Base.ts
  src/types/config/index.ts
  src/types/hooks/index.ts
  src/types/index.ts
  src/ui/hooks/wallet/__tests__/useCryptKeeperWallet.test.ts
  src/ui/hooks/wallet/__tests__/useEthWallet.test.ts
  src/ui/hooks/wallet/index.ts
  src/ui/hooks/wallet/useCryptKeeper.ts
  src/ui/hooks/wallet/useEthWallet.ts
  src/ui/pages/Home/components/Info/Info.tsx
  src/ui/pages/Home/useHome.ts
  src/ui/pages/Popup/__tests__/usePopup.test.ts
  src/ui/pages/Popup/usePopup.ts
Labels: 🖼️ ui logic, 🌱 new feature

#418 feat: account menu
  e2e/pages/cryptKeeper/CryptKeeper.ts
  src/config/mock/wallet.ts
  src/types/hooks/index.ts
  src/ui/components/AccountMenu/AccountMenu.tsx
  src/ui/components/AccountMenu/__tests__/AccountMenu.test.tsx
  src/ui/components/AccountMenu/__tests__/useAccountMenu.test.ts
  src/ui/components/AccountMenu/index.ts
  src/ui/components/AccountMenu/useAccountMenu.ts
  src/ui/components/Header/__tests__/Header.test.tsx
  src/ui/components/Header/index.tsx
  src/ui/hooks/wallet/__tests__/useCryptKeeperWallet.test.ts
  src/ui/hooks/wallet/__tests__/useEthWallet.test.ts
  src/ui/hooks/wallet/useCryptKeeper.ts
  src/ui/hooks/wallet/useEthWallet.ts
  src/ui/pages/CreateIdentity/__tests__/CreateIdentity.test.tsx
  src/ui/pages/CreateIdentity/__tests__/useCreateIdentity.test.ts
  src/ui/pages/CreateIdentity/useCreateIdentity.ts
  src/ui/pages/DownloadBackup/__tests__/DownloadBackup.test.tsx
  src/ui/pages/Home/__tests__/Home.test.tsx
  src/ui/pages/Popup/__tests__/Popup.test.tsx
  src/ui/pages/Settings/__tests__/Settings.test.tsx
  src/ui/theme.ts
Labels: 🖼️ ui logic, 🖌️ ui design, 🌱 new feature
